//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGMA.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accesos()
        {
            this.Accesos1 = new HashSet<Accesos>();
            this.RolesAccesos = new HashSet<RolesAccesos>();
        }
    
        public int IdAcceso { get; set; }
        public Nullable<int> IdAccesoPadre { get; set; }
        public int IdCategoriaAcceso { get; set; }
        public string NombreAcceso { get; set; }
        public string Descripcion { get; set; }
        public string Icono { get; set; }
        public string UrlAcceso { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accesos> Accesos1 { get; set; }
        public virtual Accesos Accesos2 { get; set; }
        public virtual CategoriasAcceso CategoriasAcceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesAccesos> RolesAccesos { get; set; }
    }
}
