//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGMA.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosDiarios
    {
        public int IdGastoDiario { get; set; }
        public Nullable<int> IdOperario { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public decimal Monto { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Operarios Operarios { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
