//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGMA.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int IdNotificacion { get; set; }
        public int IdOperario { get; set; }
        public string TituloNotificacion { get; set; }
        public string Descripcion { get; set; }
        public string Color { get; set; }
        public string Icono { get; set; }
        public int IdNivel { get; set; }
        public System.DateTime FechaHora { get; set; }
        public bool Estado { get; set; }
    
        public virtual NivelNotificacion NivelNotificacion { get; set; }
        public virtual Operarios Operarios { get; set; }
    }
}
