//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGMA.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdSubcategorias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProdSubcategorias()
        {
            this.ProdProducto = new HashSet<ProdProducto>();
        }
    
        public int IdSubcategoria { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string Subcategoria { get; set; }
        public bool Estado { get; set; }
    
        public virtual ProdCategorias ProdCategorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdProducto> ProdProducto { get; set; }
    }
}
