//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGMA.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesAccesos
    {
        public int IdRolAcceso { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<int> IdAcceso { get; set; }
    
        public virtual Accesos Accesos { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
