//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGMA.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SisGMAEntities : DbContext
    {
        public SisGMAEntities()
            : base("name=SisGMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accesos> Accesos { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<CategoriasAcceso> CategoriasAcceso { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<ClientesVehiculos> ClientesVehiculos { get; set; }
        public virtual DbSet<Comunas> Comunas { get; set; }
        public virtual DbSet<ControlProduccion> ControlProduccion { get; set; }
        public virtual DbSet<GastosDiarios> GastosDiarios { get; set; }
        public virtual DbSet<Giros> Giros { get; set; }
        public virtual DbSet<MarcaProductos> MarcaProductos { get; set; }
        public virtual DbSet<MarcaVehiculos> MarcaVehiculos { get; set; }
        public virtual DbSet<ModeloVehiculos> ModeloVehiculos { get; set; }
        public virtual DbSet<NivelNotificacion> NivelNotificacion { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
        public virtual DbSet<Operarios> Operarios { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Regiones> Regiones { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RolesAccesos> RolesAccesos { get; set; }
        public virtual DbSet<Subcategorias> Subcategorias { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
    }
}
