//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGMA.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SisGMAEntities : DbContext
    {
        public SisGMAEntities()
            : base("name=SisGMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CliClientes> CliClientes { get; set; }
        public virtual DbSet<CtrlControlProduccion> CtrlControlProduccion { get; set; }
        public virtual DbSet<GastGastosDiarios> GastGastosDiarios { get; set; }
        public virtual DbSet<GenComunas> GenComunas { get; set; }
        public virtual DbSet<GenGiros> GenGiros { get; set; }
        public virtual DbSet<GenProvincias> GenProvincias { get; set; }
        public virtual DbSet<GenRegiones> GenRegiones { get; set; }
        public virtual DbSet<GenRoles> GenRoles { get; set; }
        public virtual DbSet<OpOperarios> OpOperarios { get; set; }
        public virtual DbSet<ProdCategorias> ProdCategorias { get; set; }
        public virtual DbSet<ProdMarcas> ProdMarcas { get; set; }
        public virtual DbSet<ProdProducto> ProdProducto { get; set; }
        public virtual DbSet<ProdSubcategorias> ProdSubcategorias { get; set; }
        public virtual DbSet<ProvProveedores> ProvProveedores { get; set; }
        public virtual DbSet<VehMarcas> VehMarcas { get; set; }
        public virtual DbSet<VehModelos> VehModelos { get; set; }
        public virtual DbSet<VehVehiculos> VehVehiculos { get; set; }
    }
}
