//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGMA.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculos()
        {
            this.ClientesVehiculos = new HashSet<ClientesVehiculos>();
        }
    
        public int IdVehiculo { get; set; }
        public int IdModelo { get; set; }
        public string Patente { get; set; }
        public int KmIngreso { get; set; }
        public int Anio { get; set; }
        public string Color { get; set; }
        public int Estanque { get; set; }
        public string Observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesVehiculos> ClientesVehiculos { get; set; }
        public virtual ModeloVehiculos ModeloVehiculos { get; set; }
    }
}
