//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGMA.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctrl_ControlProduccion
    {
        public int IdControlProd { get; set; }
        public Nullable<int> IdOperario { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public decimal ValorNeto { get; set; }
    
        public virtual Op_Operarios Op_Operarios { get; set; }
    }
}
