//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGMA.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Giros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gen_Giros()
        {
            this.Prov_Proveedores = new HashSet<Prov_Proveedores>();
        }
    
        public int IdGiro { get; set; }
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Iva { get; set; }
        public Nullable<int> CatTributaria { get; set; }
        public Nullable<int> Internet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prov_Proveedores> Prov_Proveedores { get; set; }
    }
}
