//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGMA.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Op_Operarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Op_Operarios()
        {
            this.Ctrl_ControlProduccion = new HashSet<Ctrl_ControlProduccion>();
            this.Gast_GastosDiarios = new HashSet<Gast_GastosDiarios>();
        }
    
        public int IdOperario { get; set; }
        public string RutOperario { get; set; }
        public string Nombres { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> IdComuna { get; set; }
        public int Telefono { get; set; }
        public Nullable<int> IdRol { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ctrl_ControlProduccion> Ctrl_ControlProduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gast_GastosDiarios> Gast_GastosDiarios { get; set; }
        public virtual Gen_Comunas Gen_Comunas { get; set; }
        public virtual Gen_Roles Gen_Roles { get; set; }
    }
}
