//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGMA.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_Producto
    {
        public int IdProducto { get; set; }
        public Nullable<int> IdSubcategoria { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public decimal ValorIngreso { get; set; }
        public decimal ValorSalida { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Prod_Marcas Prod_Marcas { get; set; }
        public virtual Prod_Subcategorias Prod_Subcategorias { get; set; }
        public virtual Prov_Proveedores Prov_Proveedores { get; set; }
    }
}
