USE SisGMA
GO

INSERT  INTO Provincias
        ( IdProvincia, IdRegion, Provincia )
VALUES  ( 1, 1, 'Provincia de Arica' ),
        ( 2, 1, 'Provincia de Parinacota' ),
        ( 3, 2, 'Provincia de Iquique' ),
        ( 4, 2, 'Provincia Del Tamarugal' ),
        ( 5, 3, 'Provincia de Tocopilla' ),
        ( 6, 3, 'Provincia de El Loa' ),
        ( 7, 3, 'Provincia de Antofagasta' ),
        ( 8, 4, 'Provincia de Chañaral' ),
        ( 9, 4, 'Provincia de Copiapó' ),
        ( 10, 4, 'Provincia de Huasco' ),
        ( 11, 5, 'Provincia de  Elqui' ),
        ( 12, 5, 'Provincia de Limarí' ),
        ( 13, 5, 'Provincia de Choapa' ),
        ( 14, 6, 'Provincia de Petorca' ),
        ( 15, 6, 'Provincia de Los Andes' ),
        ( 16, 6, 'Provincia de San Felipe de Aconcagua' ),
        ( 17, 6, 'Provincia de Quillota' ),
        ( 18, 6, 'Provincia de Marga Marga' ),
        ( 19, 6, 'Provincia de Valparaíso' ),
        ( 20, 6, 'Provincia de San Antonio' ),
        ( 21, 6, 'Provincia de Isla de Pascua' ),
        ( 22, 7, 'Provincia de Cachapoal' ),
        ( 23, 7, 'Provincia de Colchagua' ),
        ( 24, 7, 'Provincia Cardenal Caro' ),
        ( 25, 8, 'Provincia de Curicó' ),
        ( 26, 8, 'Provincia de Talca' ),
        ( 27, 8, 'Provincia de Linares' ),
        ( 28, 8, 'Provincia de Cauquenes' ),
        ( 29, 9, 'Provincia de Ñuble' ),
        ( 30, 9, 'Provincia de Bío Bío' ),
        ( 31, 9, 'Provincia de Concepción' ),
        ( 32, 9, 'Provincia de Arauco' ),
        ( 33, 10, 'Provincia de Malleco' ),
        ( 34, 10, 'Provincia de Cautín' ),
        ( 35, 11, 'Provincia de Valdivia' ),
        ( 36, 11, 'Provincia de Ranco' ),
        ( 37, 12, 'Provincia de Osorno' ),
        ( 38, 12, 'Provincia de Llanquihue' ),
        ( 39, 12, 'Provincia de Chiloé' ),
        ( 40, 12, 'Provincia de Palena' ),
        ( 41, 13, 'Provincia de Coihaique' ),
        ( 42, 13, 'Provincia de Aisén' ),
        ( 43, 13, 'Provincia de General Carrera' ),
        ( 44, 13, 'Provincia de Capitán Prat' ),
        ( 45, 14, 'Provincia de Ultima Esperanza' ),
        ( 46, 14, 'Provincia de Magallanes' ),
        ( 47, 14, 'Provincia de Tierra del Fuego' ),
        ( 48, 14, 'Provincia de Antártica Chilena' ),
        ( 49, 15, 'Provincia de Santiago' ),
        ( 50, 15, 'Provincia de Chacabuco' ),
        ( 51, 15, 'Provincia de Cordillera' ),
        ( 52, 15, 'Provincia de Maipo' ),
        ( 53, 15, 'Provincia de Melipilla' ),
        ( 54, 15, 'Provincia de Talagante' )
GO
