USE SisGMA
GO

INSERT INTO Gen_Provincias VALUES (1,1,'Provincia de Arica')
INSERT INTO Gen_Provincias VALUES (2,1,'Provincia de Parinacota')
INSERT INTO Gen_Provincias VALUES (3,2,'Provincia de Iquique')
INSERT INTO Gen_Provincias VALUES (4,2,'Provincia Del Tamarugal')
INSERT INTO Gen_Provincias VALUES (5,3,'Provincia de Tocopilla')
INSERT INTO Gen_Provincias VALUES (6,3,'Provincia de El Loa')
INSERT INTO Gen_Provincias VALUES (7,3,'Provincia de Antofagasta')
INSERT INTO Gen_Provincias VALUES (8,4,'Provincia de Chañaral')
INSERT INTO Gen_Provincias VALUES (9,4,'Provincia de Copiapó')
INSERT INTO Gen_Provincias VALUES (10,4,'Provincia de Huasco')
INSERT INTO Gen_Provincias VALUES (11,5,'Provincia de  Elqui')
INSERT INTO Gen_Provincias VALUES (12,5,'Provincia de Limarí')
INSERT INTO Gen_Provincias VALUES (13,5,'Provincia de Choapa')
INSERT INTO Gen_Provincias VALUES (14,6,'Provincia de Petorca')
INSERT INTO Gen_Provincias VALUES (15,6,'Provincia de Los Andes')
INSERT INTO Gen_Provincias VALUES (16,6,'Provincia de San Felipe de Aconcagua')
INSERT INTO Gen_Provincias VALUES (17,6,'Provincia de Quillota')
INSERT INTO Gen_Provincias VALUES (18,6,'Provincia de Marga Marga')
INSERT INTO Gen_Provincias VALUES (19,6,'Provincia de Valparaíso')
INSERT INTO Gen_Provincias VALUES (20,6,'Provincia de San Antonio')
INSERT INTO Gen_Provincias VALUES (21,6,'Provincia de Isla de Pascua')
INSERT INTO Gen_Provincias VALUES (22,7,'Provincia de Cachapoal')
INSERT INTO Gen_Provincias VALUES (23,7,'Provincia de Colchagua')
INSERT INTO Gen_Provincias VALUES (24,7,'Provincia Cardenal Caro')
INSERT INTO Gen_Provincias VALUES (25,8,'Provincia de Curicó')
INSERT INTO Gen_Provincias VALUES (26,8,'Provincia de Talca')
INSERT INTO Gen_Provincias VALUES (27,8,'Provincia de Linares')
INSERT INTO Gen_Provincias VALUES (28,8,'Provincia de Cauquenes')
INSERT INTO Gen_Provincias VALUES (29,9,'Provincia de Ñuble')
INSERT INTO Gen_Provincias VALUES (30,9,'Provincia de Bío Bío')
INSERT INTO Gen_Provincias VALUES (31,9,'Provincia de Concepción')
INSERT INTO Gen_Provincias VALUES (32,9,'Provincia de Arauco')
INSERT INTO Gen_Provincias VALUES (33,10,'Provincia de Malleco')
INSERT INTO Gen_Provincias VALUES (34,10,'Provincia de Cautín')
INSERT INTO Gen_Provincias VALUES (35,11,'Provincia de Valdivia')
INSERT INTO Gen_Provincias VALUES (36,11,'Provincia de Ranco')
INSERT INTO Gen_Provincias VALUES (37,12,'Provincia de Osorno')
INSERT INTO Gen_Provincias VALUES (38,12,'Provincia de Llanquihue')
INSERT INTO Gen_Provincias VALUES (39,12,'Provincia de Chiloé')
INSERT INTO Gen_Provincias VALUES (40,12,'Provincia de Palena')
INSERT INTO Gen_Provincias VALUES (41,13,'Provincia de Coihaique')
INSERT INTO Gen_Provincias VALUES (42,13,'Provincia de Aisén')
INSERT INTO Gen_Provincias VALUES (43,13,'Provincia de General Carrera')
INSERT INTO Gen_Provincias VALUES (44,13,'Provincia de Capitán Prat')
INSERT INTO Gen_Provincias VALUES (45,14,'Provincia de Ultima Esperanza')
INSERT INTO Gen_Provincias VALUES (46,14,'Provincia de Magallanes')
INSERT INTO Gen_Provincias VALUES (47,14,'Provincia de Tierra del Fuego')
INSERT INTO Gen_Provincias VALUES (48,14,'Provincia de Antártica Chilena')
INSERT INTO Gen_Provincias VALUES (49,15,'Provincia de Santiago')
INSERT INTO Gen_Provincias VALUES (50,15,'Provincia de Chacabuco')
INSERT INTO Gen_Provincias VALUES (51,15,'Provincia de Cordillera')
INSERT INTO Gen_Provincias VALUES (52,15,'Provincia de Maipo')
INSERT INTO Gen_Provincias VALUES (53,15,'Provincia de Melipilla')
INSERT INTO Gen_Provincias VALUES (54,15,'Provincia de Talagante')
