USE SisGMA
GO

INSERT INTO Provincias VALUES (1, 1, 'Provincia de Arica')
INSERT INTO Provincias VALUES (2, 1, 'Provincia de Parinacota')
INSERT INTO Provincias VALUES (3, 2, 'Provincia de Iquique')
INSERT INTO Provincias VALUES (4, 2, 'Provincia Del Tamarugal')
INSERT INTO Provincias VALUES (5, 3, 'Provincia de Tocopilla')
INSERT INTO Provincias VALUES (6, 3, 'Provincia de El Loa')
INSERT INTO Provincias VALUES (7, 3, 'Provincia de Antofagasta')
INSERT INTO Provincias VALUES (8, 4, 'Provincia de Chañaral')
INSERT INTO Provincias VALUES (9, 4, 'Provincia de Copiapó')
INSERT INTO Provincias VALUES (10, 4, 'Provincia de Huasco')
INSERT INTO Provincias VALUES (11, 5, 'Provincia de  Elqui')
INSERT INTO Provincias VALUES (12, 5, 'Provincia de Limarí')
INSERT INTO Provincias VALUES (13, 5, 'Provincia de Choapa')
INSERT INTO Provincias VALUES (14, 6, 'Provincia de Petorca')
INSERT INTO Provincias VALUES (15, 6, 'Provincia de Los Andes')
INSERT INTO Provincias VALUES (16, 6, 'Provincia de San Felipe de Aconcagua')
INSERT INTO Provincias VALUES (17, 6, 'Provincia de Quillota')
INSERT INTO Provincias VALUES (18, 6, 'Provincia de Marga Marga')
INSERT INTO Provincias VALUES (19, 6, 'Provincia de Valparaíso')
INSERT INTO Provincias VALUES (20, 6, 'Provincia de San Antonio')
INSERT INTO Provincias VALUES (21, 6, 'Provincia de Isla de Pascua')
INSERT INTO Provincias VALUES (22, 7, 'Provincia de Cachapoal')
INSERT INTO Provincias VALUES (23, 7, 'Provincia de Colchagua')
INSERT INTO Provincias VALUES (24, 7, 'Provincia Cardenal Caro')
INSERT INTO Provincias VALUES (25, 8, 'Provincia de Curicó')
INSERT INTO Provincias VALUES (26, 8, 'Provincia de Talca')
INSERT INTO Provincias VALUES (27, 8, 'Provincia de Linares')
INSERT INTO Provincias VALUES (28, 8, 'Provincia de Cauquenes')
INSERT INTO Provincias VALUES (29, 9, 'Provincia de Ñuble')
INSERT INTO Provincias VALUES (30, 9, 'Provincia de Bío Bío')
INSERT INTO Provincias VALUES (31, 9, 'Provincia de Concepción')
INSERT INTO Provincias VALUES (32, 9, 'Provincia de Arauco')
INSERT INTO Provincias VALUES (33, 10, 'Provincia de Malleco')
INSERT INTO Provincias VALUES (34, 10, 'Provincia de Cautín')
INSERT INTO Provincias VALUES (35, 11, 'Provincia de Valdivia')
INSERT INTO Provincias VALUES (36, 11, 'Provincia de Ranco')
INSERT INTO Provincias VALUES (37, 12, 'Provincia de Osorno')
INSERT INTO Provincias VALUES (38, 12, 'Provincia de Llanquihue')
INSERT INTO Provincias VALUES (39, 12, 'Provincia de Chiloé')
INSERT INTO Provincias VALUES (40, 12, 'Provincia de Palena')
INSERT INTO Provincias VALUES (41, 13, 'Provincia de Coihaique')
INSERT INTO Provincias VALUES (42, 13, 'Provincia de Aisén')
INSERT INTO Provincias VALUES (43, 13, 'Provincia de General Carrera')
INSERT INTO Provincias VALUES (44, 13, 'Provincia de Capitán Prat')
INSERT INTO Provincias VALUES (45, 14, 'Provincia de Ultima Esperanza')
INSERT INTO Provincias VALUES (46, 14, 'Provincia de Magallanes')
INSERT INTO Provincias VALUES (47, 14, 'Provincia de Tierra del Fuego')
INSERT INTO Provincias VALUES (48, 14, 'Provincia de Antártica Chilena')
INSERT INTO Provincias VALUES (49, 15, 'Provincia de Santiago')
INSERT INTO Provincias VALUES (50, 15, 'Provincia de Chacabuco')
INSERT INTO Provincias VALUES (51, 15, 'Provincia de Cordillera')
INSERT INTO Provincias VALUES (52, 15, 'Provincia de Maipo')
INSERT INTO Provincias VALUES (53, 15, 'Provincia de Melipilla')
INSERT INTO Provincias VALUES (54, 15, 'Provincia de Talagante')
