USE SisGMA
GO

INSERT INTO Comunas VALUES (1, 1, 'Arica')
INSERT INTO Comunas VALUES (2, 1, 'Camarones')
INSERT INTO Comunas VALUES (3, 2, 'Putre')
INSERT INTO Comunas VALUES (4, 2, 'General Lagos')
INSERT INTO Comunas VALUES (5, 3, 'Alto Hospicio')
INSERT INTO Comunas VALUES (6, 3, 'Iquique')
INSERT INTO Comunas VALUES (7, 4, 'Huara')
INSERT INTO Comunas VALUES (8, 4, 'Camiña')
INSERT INTO Comunas VALUES (9, 4, 'Colchane')
INSERT INTO Comunas VALUES (10, 4, 'Pica')
INSERT INTO Comunas VALUES (11, 4, 'Pozo Almonte')
INSERT INTO Comunas VALUES (12, 5, 'Tocopilla')
INSERT INTO Comunas VALUES (13, 5, 'María Elena')
INSERT INTO Comunas VALUES (14, 6, 'Calama')
INSERT INTO Comunas VALUES (15, 6, 'Ollagüe')
INSERT INTO Comunas VALUES (16, 6, 'San Pedro de Atacama')
INSERT INTO Comunas VALUES (17, 7, 'Antofagasta')
INSERT INTO Comunas VALUES (18, 7, 'Mejillones')
INSERT INTO Comunas VALUES (19, 7, 'Sierra Gorda')
INSERT INTO Comunas VALUES (20, 7, 'Taltal')
INSERT INTO Comunas VALUES (21, 8, 'Chañaral')
INSERT INTO Comunas VALUES (22, 8, 'Diego de Almagro')
INSERT INTO Comunas VALUES (23, 9, 'Copiapó')
INSERT INTO Comunas VALUES (24, 9, 'Caldera')
INSERT INTO Comunas VALUES (25, 9, 'Tierra Amarilla')
INSERT INTO Comunas VALUES (26, 10, 'Vallenar')
INSERT INTO Comunas VALUES (27, 10, 'Freirina')
INSERT INTO Comunas VALUES (28, 10, 'Huasco')
INSERT INTO Comunas VALUES (29, 10, 'Alto del Carmen')
INSERT INTO Comunas VALUES (30, 11, 'La Serena')
INSERT INTO Comunas VALUES (31, 11, 'La Higuera')
INSERT INTO Comunas VALUES (32, 11, 'Coquimbo')
INSERT INTO Comunas VALUES (33, 11, 'Andacollo')
INSERT INTO Comunas VALUES (34, 11, 'Vicuña')
INSERT INTO Comunas VALUES (35, 11, 'Paihuano')
INSERT INTO Comunas VALUES (36, 12, 'Ovalle')
INSERT INTO Comunas VALUES (37, 12, 'Río Hurtado')
INSERT INTO Comunas VALUES (38, 12, 'Monte Patria')
INSERT INTO Comunas VALUES (39, 12, 'Combarbalá')
INSERT INTO Comunas VALUES (40, 12, 'Punitaqui')
INSERT INTO Comunas VALUES (41, 13, 'Illapel')
INSERT INTO Comunas VALUES (42, 13, 'Salamanca')
INSERT INTO Comunas VALUES (43, 13, 'Los Vilos')
INSERT INTO Comunas VALUES (44, 13, 'Canela')
INSERT INTO Comunas VALUES (45, 14, 'La Ligua')
INSERT INTO Comunas VALUES (46, 14, 'Petorca')
INSERT INTO Comunas VALUES (47, 14, 'Cabildo')
INSERT INTO Comunas VALUES (48, 14, 'Zapallar')
INSERT INTO Comunas VALUES (49, 14, 'Papudo')
INSERT INTO Comunas VALUES (50, 15, 'Los Andes')
INSERT INTO Comunas VALUES (51, 15, 'San Esteban')
INSERT INTO Comunas VALUES (52, 15, 'Calle Larga')
INSERT INTO Comunas VALUES (53, 15, 'Rinconada')
INSERT INTO Comunas VALUES (54, 16, 'San Felipe')
INSERT INTO Comunas VALUES (55, 16, 'Putaendo')
INSERT INTO Comunas VALUES (56, 16, 'Santa María')
INSERT INTO Comunas VALUES (57, 16, 'Panquehue')
INSERT INTO Comunas VALUES (58, 16, 'Llaillay')
INSERT INTO Comunas VALUES (59, 16, 'Catemu')
INSERT INTO Comunas VALUES (60, 17, 'Quillota')
INSERT INTO Comunas VALUES (61, 17, 'La Cruz')
INSERT INTO Comunas VALUES (62, 17, 'La Calera')
INSERT INTO Comunas VALUES (63, 17, 'Nogales')
INSERT INTO Comunas VALUES (64, 17, 'Hijuelas')
INSERT INTO Comunas VALUES (65, 18, 'Quilpué')
INSERT INTO Comunas VALUES (66, 18, 'Villa Alemana')
INSERT INTO Comunas VALUES (67, 18, 'Limache')
INSERT INTO Comunas VALUES (68, 18, 'Olmué')
INSERT INTO Comunas VALUES (69, 19, 'Valparaíso')
INSERT INTO Comunas VALUES (70, 19, 'Viña del Mar')
INSERT INTO Comunas VALUES (71, 19, 'Quintero')
INSERT INTO Comunas VALUES (72, 19, 'Puchuncaví')
INSERT INTO Comunas VALUES (73, 19, 'Casablanca')
INSERT INTO Comunas VALUES (74, 19, 'Concón')
INSERT INTO Comunas VALUES (75, 19, 'Juan Fernández')
INSERT INTO Comunas VALUES (76, 20, 'San Antonio')
INSERT INTO Comunas VALUES (77, 20, 'Cartagena')
INSERT INTO Comunas VALUES (78, 20, 'El Tabo')
INSERT INTO Comunas VALUES (79, 20, 'El Quisco')
INSERT INTO Comunas VALUES (80, 20, 'Algarrobo')
INSERT INTO Comunas VALUES (81, 20, 'Santo Domingo')
INSERT INTO Comunas VALUES (82, 21, 'Isla de Pascua')
INSERT INTO Comunas VALUES (83, 22, 'Rancagua')
INSERT INTO Comunas VALUES (84, 22, 'Graneros')
INSERT INTO Comunas VALUES (85, 22, 'Mostazal')
INSERT INTO Comunas VALUES (86, 22, 'Codegua')
INSERT INTO Comunas VALUES (87, 22, 'Machalí')
INSERT INTO Comunas VALUES (88, 22, 'Olivar')
INSERT INTO Comunas VALUES (89, 22, 'Requínoa')
INSERT INTO Comunas VALUES (90, 22, 'Rengo')
INSERT INTO Comunas VALUES (91, 22, 'Malloa')
INSERT INTO Comunas VALUES (92, 22, 'Quinta de Tilcoco')
INSERT INTO Comunas VALUES (93, 22, 'San Vicente de Tagua Tagua')
INSERT INTO Comunas VALUES (94, 22, 'Pichidegua')
INSERT INTO Comunas VALUES (95, 22, 'Peumo')
INSERT INTO Comunas VALUES (96, 22, 'Coltauco')
INSERT INTO Comunas VALUES (97, 22, 'Coínco')
INSERT INTO Comunas VALUES (98, 22, 'Doñihue')
INSERT INTO Comunas VALUES (99, 22, 'Las Cabras')
INSERT INTO Comunas VALUES (100, 23, 'San Fernando')
INSERT INTO Comunas VALUES (101, 23, 'Chimbarongo')
INSERT INTO Comunas VALUES (102, 23, 'Placilla')
INSERT INTO Comunas VALUES (103, 23, 'Nancagua')
INSERT INTO Comunas VALUES (104, 23, 'Chépica')
INSERT INTO Comunas VALUES (105, 23, 'Santa Cruz')
INSERT INTO Comunas VALUES (106, 23, 'Lolol')
INSERT INTO Comunas VALUES (107, 23, 'Pumanque')
INSERT INTO Comunas VALUES (108, 23, 'Palmilla')
INSERT INTO Comunas VALUES (109, 23, 'Peralillo')
INSERT INTO Comunas VALUES (110, 24, 'Pichilemu')
INSERT INTO Comunas VALUES (111, 24, 'Navidad')
INSERT INTO Comunas VALUES (112, 24, 'Litueche')
INSERT INTO Comunas VALUES (113, 24, 'La Estrella')
INSERT INTO Comunas VALUES (114, 24, 'Marchigüe')
INSERT INTO Comunas VALUES (115, 24, 'Paredones')
INSERT INTO Comunas VALUES (116, 25, 'Curicó')
INSERT INTO Comunas VALUES (117, 25, 'Teno')
INSERT INTO Comunas VALUES (118, 25, 'Romeral')
INSERT INTO Comunas VALUES (119, 25, 'Molina')
INSERT INTO Comunas VALUES (120, 25, 'Sagrada Familia')
INSERT INTO Comunas VALUES (121, 25, 'Hualañé')
INSERT INTO Comunas VALUES (122, 25, 'Licantén')
INSERT INTO Comunas VALUES (123, 25, 'Vichuquén')
INSERT INTO Comunas VALUES (124, 25, 'Rauco')
INSERT INTO Comunas VALUES (125, 26, 'Talca')
INSERT INTO Comunas VALUES (126, 26, 'Pelarco')
INSERT INTO Comunas VALUES (127, 26, 'Río Claro')
INSERT INTO Comunas VALUES (128, 26, 'San Clemente')
INSERT INTO Comunas VALUES (129, 26, 'Maule')
INSERT INTO Comunas VALUES (130, 26, 'San Rafael')
INSERT INTO Comunas VALUES (131, 26, 'Empedrado')
INSERT INTO Comunas VALUES (132, 26, 'Pencahue')
INSERT INTO Comunas VALUES (133, 26, 'Constitución')
INSERT INTO Comunas VALUES (134, 26, 'Curepto')
INSERT INTO Comunas VALUES (135, 27, 'Linares')
INSERT INTO Comunas VALUES (136, 27, 'Yerbas Buenas')
INSERT INTO Comunas VALUES (137, 27, 'Colbún')
INSERT INTO Comunas VALUES (138, 27, 'Longaví')
INSERT INTO Comunas VALUES (139, 27, 'Parral')
INSERT INTO Comunas VALUES (140, 27, 'Retiro')
INSERT INTO Comunas VALUES (141, 27, 'Villa Alegre')
INSERT INTO Comunas VALUES (142, 27, 'San Javier de Loncomilla')
INSERT INTO Comunas VALUES (143, 28, 'Cauquenes')
INSERT INTO Comunas VALUES (144, 28, 'Pelluhue')
INSERT INTO Comunas VALUES (145, 28, 'Chanco')
INSERT INTO Comunas VALUES (146, 29, 'Chillán')
INSERT INTO Comunas VALUES (147, 29, 'San Carlos')
INSERT INTO Comunas VALUES (148, 29, 'Ñiquén')
INSERT INTO Comunas VALUES (149, 29, 'San Fabián')
INSERT INTO Comunas VALUES (150, 29, 'Coihueco')
INSERT INTO Comunas VALUES (151, 29, 'Pinto')
INSERT INTO Comunas VALUES (152, 29, 'San Ignacio')
INSERT INTO Comunas VALUES (153, 29, 'El Carmen')
INSERT INTO Comunas VALUES (154, 29, 'Yungay')
INSERT INTO Comunas VALUES (155, 29, 'Pemuco')
INSERT INTO Comunas VALUES (156, 29, 'Bulnes')
INSERT INTO Comunas VALUES (157, 29, 'Quillón')
INSERT INTO Comunas VALUES (158, 29, 'Ránquil')
INSERT INTO Comunas VALUES (159, 29, 'Portezuelo')
INSERT INTO Comunas VALUES (160, 29, 'Coelemu')
INSERT INTO Comunas VALUES (161, 29, 'Treguaco')
INSERT INTO Comunas VALUES (162, 29, 'Cobquecura')
INSERT INTO Comunas VALUES (163, 29, 'Quirihue')
INSERT INTO Comunas VALUES (164, 29, 'Ninhue')
INSERT INTO Comunas VALUES (165, 29, 'San Nicolás')
INSERT INTO Comunas VALUES (166, 29, 'Chillán Viejo')
INSERT INTO Comunas VALUES (167, 30, 'Alto Bío Bío')
INSERT INTO Comunas VALUES (168, 30, 'Los Ángeles')
INSERT INTO Comunas VALUES (169, 30, 'Cabrero')
INSERT INTO Comunas VALUES (170, 30, 'Tucapel')
INSERT INTO Comunas VALUES (171, 30, 'Antuco')
INSERT INTO Comunas VALUES (172, 30, 'Quilleco')
INSERT INTO Comunas VALUES (173, 30, 'Santa Bárbara')
INSERT INTO Comunas VALUES (174, 30, 'Quilaco')
INSERT INTO Comunas VALUES (175, 30, 'Mulchén')
INSERT INTO Comunas VALUES (176, 30, 'Negrete')
INSERT INTO Comunas VALUES (177, 30, 'Nacimiento')
INSERT INTO Comunas VALUES (178, 30, 'Laja')
INSERT INTO Comunas VALUES (179, 30, 'San Rosendo')
INSERT INTO Comunas VALUES (180, 30, 'Yumbel')
INSERT INTO Comunas VALUES (181, 31, 'Concepción')
INSERT INTO Comunas VALUES (182, 31, 'Talcahuano')
INSERT INTO Comunas VALUES (183, 31, 'Penco')
INSERT INTO Comunas VALUES (184, 31, 'Tomé')
INSERT INTO Comunas VALUES (185, 31, 'Florida')
INSERT INTO Comunas VALUES (186, 31, 'Hualpén')
INSERT INTO Comunas VALUES (187, 31, 'Hualqui')
INSERT INTO Comunas VALUES (188, 31, 'Santa Juana')
INSERT INTO Comunas VALUES (189, 31, 'Lota')
INSERT INTO Comunas VALUES (190, 31, 'Coronel')
INSERT INTO Comunas VALUES (191, 31, 'San Pedro de la Paz')
INSERT INTO Comunas VALUES (192, 31, 'Chiguayante')
INSERT INTO Comunas VALUES (193, 32, 'Lebu')
INSERT INTO Comunas VALUES (194, 32, 'Arauco')
INSERT INTO Comunas VALUES (195, 32, 'Curanilahue')
INSERT INTO Comunas VALUES (196, 32, 'Los Álamos')
INSERT INTO Comunas VALUES (197, 32, 'Cañete')
INSERT INTO Comunas VALUES (198, 32, 'Contulmo')
INSERT INTO Comunas VALUES (199, 32, 'Tirúa')
INSERT INTO Comunas VALUES (200, 33, 'Angol')
INSERT INTO Comunas VALUES (201, 33, 'Renaico')
INSERT INTO Comunas VALUES (202, 33, 'Collipulli')
INSERT INTO Comunas VALUES (203, 33, 'Lonquimay')
INSERT INTO Comunas VALUES (204, 33, 'Curacautín')
INSERT INTO Comunas VALUES (205, 33, 'Ercilla')
INSERT INTO Comunas VALUES (206, 33, 'Victoria')
INSERT INTO Comunas VALUES (207, 33, 'Traiguén')
INSERT INTO Comunas VALUES (208, 33, 'Lumaco')
INSERT INTO Comunas VALUES (209, 33, 'Purén')
INSERT INTO Comunas VALUES (210, 33, 'Los Sauces')
INSERT INTO Comunas VALUES (211, 34, 'Temuco')
INSERT INTO Comunas VALUES (212, 34, 'Lautaro')
INSERT INTO Comunas VALUES (213, 34, 'Perquenco')
INSERT INTO Comunas VALUES (214, 34, 'Vilcún')
INSERT INTO Comunas VALUES (215, 34, 'Cholchol')
INSERT INTO Comunas VALUES (216, 34, 'Cunco')
INSERT INTO Comunas VALUES (217, 34, 'Melipeuco')
INSERT INTO Comunas VALUES (218, 34, 'Curarrehue')
INSERT INTO Comunas VALUES (219, 34, 'Pucón')
INSERT INTO Comunas VALUES (220, 34, 'Villarrica')
INSERT INTO Comunas VALUES (221, 34, 'Freire')
INSERT INTO Comunas VALUES (222, 34, 'Pitrufquén')
INSERT INTO Comunas VALUES (223, 34, 'Gorbea')
INSERT INTO Comunas VALUES (224, 34, 'Loncoche')
INSERT INTO Comunas VALUES (225, 34, 'Toltén')
INSERT INTO Comunas VALUES (226, 34, 'Teodoro Schmidt')
INSERT INTO Comunas VALUES (227, 34, 'Saavedra')
INSERT INTO Comunas VALUES (228, 34, 'Carahue')
INSERT INTO Comunas VALUES (229, 34, 'Nueva Imperial')
INSERT INTO Comunas VALUES (230, 34, 'Galvarino')
INSERT INTO Comunas VALUES (231, 34, 'Padre Las Casas')
INSERT INTO Comunas VALUES (232, 35, 'Valdivia')
INSERT INTO Comunas VALUES (233, 35, 'Mariquina')
INSERT INTO Comunas VALUES (234, 35, 'Lanco')
INSERT INTO Comunas VALUES (235, 35, 'Máfil')
INSERT INTO Comunas VALUES (236, 35, 'Corral')
INSERT INTO Comunas VALUES (237, 35, 'Los Lagos')
INSERT INTO Comunas VALUES (238, 35, 'Panguipulli')
INSERT INTO Comunas VALUES (239, 35, 'Paillaco')
INSERT INTO Comunas VALUES (240, 36, 'La Unión')
INSERT INTO Comunas VALUES (241, 36, 'Futrono')
INSERT INTO Comunas VALUES (242, 36, 'Río Bueno')
INSERT INTO Comunas VALUES (243, 36, 'Lago Ranco')
INSERT INTO Comunas VALUES (244, 37, 'Osorno')
INSERT INTO Comunas VALUES (245, 37, 'San Pablo')
INSERT INTO Comunas VALUES (246, 37, 'Puyehue')
INSERT INTO Comunas VALUES (247, 37, 'Puerto Octay')
INSERT INTO Comunas VALUES (248, 37, 'Purranque')
INSERT INTO Comunas VALUES (249, 37, 'Río Negro')
INSERT INTO Comunas VALUES (250, 37, 'San Juan de la Costa')
INSERT INTO Comunas VALUES (251, 38, 'Puerto Montt')
INSERT INTO Comunas VALUES (252, 38, 'Puerto Varas')
INSERT INTO Comunas VALUES (253, 38, 'Cochamó')
INSERT INTO Comunas VALUES (254, 38, 'Calbuco')
INSERT INTO Comunas VALUES (255, 38, 'Maullín')
INSERT INTO Comunas VALUES (256, 38, 'Los Muermos')
INSERT INTO Comunas VALUES (257, 38, 'Fresia')
INSERT INTO Comunas VALUES (258, 38, 'Llanquihue')
INSERT INTO Comunas VALUES (259, 38, 'Frutillar')
INSERT INTO Comunas VALUES (260, 39, 'Castro')
INSERT INTO Comunas VALUES (261, 39, 'Ancud')
INSERT INTO Comunas VALUES (262, 39, 'Quemchi')
INSERT INTO Comunas VALUES (263, 39, 'Dalcahue')
INSERT INTO Comunas VALUES (264, 39, 'Curaco de Vélez')
INSERT INTO Comunas VALUES (265, 39, 'Quinchao')
INSERT INTO Comunas VALUES (266, 39, 'Puqueldón')
INSERT INTO Comunas VALUES (267, 39, 'Chonchi')
INSERT INTO Comunas VALUES (268, 39, 'Queilén')
INSERT INTO Comunas VALUES (269, 39, 'Quellón')
INSERT INTO Comunas VALUES (270, 40, 'Chaitén')
INSERT INTO Comunas VALUES (271, 40, 'Hualaihué')
INSERT INTO Comunas VALUES (272, 40, 'Futaleufú')
INSERT INTO Comunas VALUES (273, 40, 'Palena')
INSERT INTO Comunas VALUES (274, 41, 'Coihaique')
INSERT INTO Comunas VALUES (275, 41, 'Lago Verde')
INSERT INTO Comunas VALUES (276, 42, 'Aisén')
INSERT INTO Comunas VALUES (277, 42, 'Cisnes')
INSERT INTO Comunas VALUES (278, 42, 'Guaitecas')
INSERT INTO Comunas VALUES (279, 43, 'Chile Chico')
INSERT INTO Comunas VALUES (280, 43, 'Río Ibáñez')
INSERT INTO Comunas VALUES (281, 44, 'Cochrane')
INSERT INTO Comunas VALUES (282, 44, 'O''Higgins')
INSERT INTO Comunas VALUES (283, 44, 'Tortel')
INSERT INTO Comunas VALUES (284, 45, 'Natales')
INSERT INTO Comunas VALUES (285, 45, 'Torres del Paine')
INSERT INTO Comunas VALUES (286, 46, 'Punta Arenas')
INSERT INTO Comunas VALUES (287, 46, 'Río Verde')
INSERT INTO Comunas VALUES (288, 46, 'Laguna Blanca')
INSERT INTO Comunas VALUES (289, 46, 'San Gregorio')
INSERT INTO Comunas VALUES (290, 47, 'Porvenir')
INSERT INTO Comunas VALUES (291, 47, 'Primavera')
INSERT INTO Comunas VALUES (292, 47, 'Timaukel')
INSERT INTO Comunas VALUES (293, 48, 'Cabo de Hornos')
INSERT INTO Comunas VALUES (294, 48, 'Antártica')
INSERT INTO Comunas VALUES (295, 49, 'Santiago')
INSERT INTO Comunas VALUES (296, 49, 'Independencia')
INSERT INTO Comunas VALUES (297, 49, 'Conchalí')
INSERT INTO Comunas VALUES (298, 49, 'Huechuraba')
INSERT INTO Comunas VALUES (299, 49, 'Recoleta')
INSERT INTO Comunas VALUES (300, 49, 'Providencia')
INSERT INTO Comunas VALUES (301, 49, 'Vitacura')
INSERT INTO Comunas VALUES (302, 49, 'Lo Barnechea')
INSERT INTO Comunas VALUES (303, 49, 'Las Condes')
INSERT INTO Comunas VALUES (304, 49, 'Ñuñoa')
INSERT INTO Comunas VALUES (305, 49, 'La Reina')
INSERT INTO Comunas VALUES (306, 49, 'Macul')
INSERT INTO Comunas VALUES (307, 49, 'Peñalolén')
INSERT INTO Comunas VALUES (308, 49, 'La Florida')
INSERT INTO Comunas VALUES (309, 49, 'San Joaquín')
INSERT INTO Comunas VALUES (310, 49, 'La Granja')
INSERT INTO Comunas VALUES (311, 49, 'La Pintana')
INSERT INTO Comunas VALUES (312, 49, 'San Ramón')
INSERT INTO Comunas VALUES (313, 49, 'San Miguel')
INSERT INTO Comunas VALUES (314, 49, 'La Cisterna')
INSERT INTO Comunas VALUES (315, 49, 'El Bosque')
INSERT INTO Comunas VALUES (316, 49, 'Pedro Aguirre Cerda')
INSERT INTO Comunas VALUES (317, 49, 'Lo Espejo')
INSERT INTO Comunas VALUES (318, 49, 'Estación Central')
INSERT INTO Comunas VALUES (319, 49, 'Cerrillos')
INSERT INTO Comunas VALUES (320, 49, 'Maipú')
INSERT INTO Comunas VALUES (321, 49, 'Quinta Normal')
INSERT INTO Comunas VALUES (322, 49, 'Lo Prado')
INSERT INTO Comunas VALUES (323, 49, 'Pudahuel')
INSERT INTO Comunas VALUES (324, 49, 'Cerro Navia')
INSERT INTO Comunas VALUES (325, 49, 'Renca')
INSERT INTO Comunas VALUES (326, 49, 'Quilicura')
INSERT INTO Comunas VALUES (327, 50, 'Colina')
INSERT INTO Comunas VALUES (328, 50, 'Lampa')
INSERT INTO Comunas VALUES (329, 50, 'Tiltil')
INSERT INTO Comunas VALUES (330, 51, 'Puente Alto')
INSERT INTO Comunas VALUES (331, 51, 'San José de Maipo')
INSERT INTO Comunas VALUES (332, 51, 'Pirque')
INSERT INTO Comunas VALUES (333, 52, 'San Bernardo')
INSERT INTO Comunas VALUES (334, 52, 'Buin')
INSERT INTO Comunas VALUES (335, 52, 'Paine')
INSERT INTO Comunas VALUES (336, 52, 'Calera de Tango')
INSERT INTO Comunas VALUES (337, 53, 'Melipilla')
INSERT INTO Comunas VALUES (338, 53, 'María Pinto')
INSERT INTO Comunas VALUES (339, 53, 'Curacaví')
INSERT INTO Comunas VALUES (340, 53, 'Alhué')
INSERT INTO Comunas VALUES (341, 53, 'San Pedro')
INSERT INTO Comunas VALUES (342, 54, 'Talagante')
INSERT INTO Comunas VALUES (343, 54, 'Peñaflor')
INSERT INTO Comunas VALUES (344, 54, 'Isla de Maipo')
INSERT INTO Comunas VALUES (345, 54, 'El Monte')
INSERT INTO Comunas VALUES (346, 54, 'Padre Hurtado')
