USE SisGMA
GO

INSERT INTO ModeloVehiculos VALUES (1, 1, '500')
INSERT INTO ModeloVehiculos VALUES (2, 1, 'Grande Punto')
INSERT INTO ModeloVehiculos VALUES (3, 1, 'Punto Evo')
INSERT INTO ModeloVehiculos VALUES (4, 1, '500c')
INSERT INTO ModeloVehiculos VALUES (5, 1, '695')
INSERT INTO ModeloVehiculos VALUES (6, 1, 'Punto')
INSERT INTO ModeloVehiculos VALUES (7, 2, '155')
INSERT INTO ModeloVehiculos VALUES (8, 2, '156')
INSERT INTO ModeloVehiculos VALUES (9, 2, '159')
INSERT INTO ModeloVehiculos VALUES (10, 2, '164')
INSERT INTO ModeloVehiculos VALUES (11, 2, '145')
INSERT INTO ModeloVehiculos VALUES (12, 2, '147')
INSERT INTO ModeloVehiculos VALUES (13, 2, '146')
INSERT INTO ModeloVehiculos VALUES (14, 2, 'Gtv')
INSERT INTO ModeloVehiculos VALUES (15, 2, 'Spider')
INSERT INTO ModeloVehiculos VALUES (16, 2, '166')
INSERT INTO ModeloVehiculos VALUES (17, 2, 'Gt')
INSERT INTO ModeloVehiculos VALUES (18, 2, 'Crosswagon')
INSERT INTO ModeloVehiculos VALUES (19, 2, 'Brera')
INSERT INTO ModeloVehiculos VALUES (20, 2, '90')
INSERT INTO ModeloVehiculos VALUES (21, 2, '75')
INSERT INTO ModeloVehiculos VALUES (22, 2, '33')
INSERT INTO ModeloVehiculos VALUES (23, 2, 'Giulietta')
INSERT INTO ModeloVehiculos VALUES (24, 2, 'Sprint')
INSERT INTO ModeloVehiculos VALUES (25, 2, 'Mito')
INSERT INTO ModeloVehiculos VALUES (26, 3, 'Expander')
INSERT INTO ModeloVehiculos VALUES (27, 3, '10')
INSERT INTO ModeloVehiculos VALUES (28, 3, '24')
INSERT INTO ModeloVehiculos VALUES (29, 3, 'Dacia')
INSERT INTO ModeloVehiculos VALUES (30, 4, 'Rocsta')
INSERT INTO ModeloVehiculos VALUES (31, 5, 'Rocsta')
INSERT INTO ModeloVehiculos VALUES (32, 6, 'Db7')
INSERT INTO ModeloVehiculos VALUES (33, 6, 'V8')
INSERT INTO ModeloVehiculos VALUES (34, 6, 'Db9')
INSERT INTO ModeloVehiculos VALUES (35, 6, 'Vanquish')
INSERT INTO ModeloVehiculos VALUES (36, 6, 'V8 Vantage')
INSERT INTO ModeloVehiculos VALUES (37, 6, 'Vantage')
INSERT INTO ModeloVehiculos VALUES (38, 6, 'Dbs')
INSERT INTO ModeloVehiculos VALUES (39, 6, 'Volante')
INSERT INTO ModeloVehiculos VALUES (40, 6, 'Virage')
INSERT INTO ModeloVehiculos VALUES (41, 6, 'Vantage V8')
INSERT INTO ModeloVehiculos VALUES (42, 6, 'Vantage V12')
INSERT INTO ModeloVehiculos VALUES (43, 6, 'Rapide')
INSERT INTO ModeloVehiculos VALUES (44, 6, 'Cygnet')
INSERT INTO ModeloVehiculos VALUES (45, 7, '80')
INSERT INTO ModeloVehiculos VALUES (46, 7, 'A4')
INSERT INTO ModeloVehiculos VALUES (47, 7, 'A6')
INSERT INTO ModeloVehiculos VALUES (48, 7, 'S6')
INSERT INTO ModeloVehiculos VALUES (49, 7, 'Coupe')
INSERT INTO ModeloVehiculos VALUES (50, 7, 'S2')
INSERT INTO ModeloVehiculos VALUES (51, 7, 'Rs2')
INSERT INTO ModeloVehiculos VALUES (52, 7, 'A8')
INSERT INTO ModeloVehiculos VALUES (53, 7, 'Cabriolet')
INSERT INTO ModeloVehiculos VALUES (54, 7, 'S8')
INSERT INTO ModeloVehiculos VALUES (55, 7, 'A3')
INSERT INTO ModeloVehiculos VALUES (56, 7, 'S4')
INSERT INTO ModeloVehiculos VALUES (57, 7, 'Tt')
INSERT INTO ModeloVehiculos VALUES (58, 7, 'S3')
INSERT INTO ModeloVehiculos VALUES (59, 7, 'Allroad Quattro')
INSERT INTO ModeloVehiculos VALUES (60, 7, 'Rs4')
INSERT INTO ModeloVehiculos VALUES (61, 7, 'A2')
INSERT INTO ModeloVehiculos VALUES (62, 7, 'Rs6')
INSERT INTO ModeloVehiculos VALUES (63, 7, 'Q7')
INSERT INTO ModeloVehiculos VALUES (64, 7, 'R8')
INSERT INTO ModeloVehiculos VALUES (65, 7, 'A5')
INSERT INTO ModeloVehiculos VALUES (66, 7, 'S5')
INSERT INTO ModeloVehiculos VALUES (67, 7, 'V8')
INSERT INTO ModeloVehiculos VALUES (68, 7, '200')
INSERT INTO ModeloVehiculos VALUES (69, 7, '100')
INSERT INTO ModeloVehiculos VALUES (70, 7, '90')
INSERT INTO ModeloVehiculos VALUES (71, 7, 'Tts')
INSERT INTO ModeloVehiculos VALUES (72, 7, 'Q5')
INSERT INTO ModeloVehiculos VALUES (73, 7, 'A4 Allroad Quattro')
INSERT INTO ModeloVehiculos VALUES (74, 7, 'Tt Rs')
INSERT INTO ModeloVehiculos VALUES (75, 7, 'Rs5')
INSERT INTO ModeloVehiculos VALUES (76, 7, 'A1')
INSERT INTO ModeloVehiculos VALUES (77, 7, 'A7')
INSERT INTO ModeloVehiculos VALUES (78, 7, 'Rs3')
INSERT INTO ModeloVehiculos VALUES (79, 7, 'Q3')
INSERT INTO ModeloVehiculos VALUES (80, 7, 'A6 Allroad Quattro')
INSERT INTO ModeloVehiculos VALUES (81, 7, 'S7')
INSERT INTO ModeloVehiculos VALUES (82, 7, 'Sq5')
INSERT INTO ModeloVehiculos VALUES (83, 8, 'Mini')
INSERT INTO ModeloVehiculos VALUES (84, 8, 'Montego')
INSERT INTO ModeloVehiculos VALUES (85, 8, 'Maestro')
INSERT INTO ModeloVehiculos VALUES (86, 8, 'Metro')
INSERT INTO ModeloVehiculos VALUES (87, 8, 'Mini Moke')
INSERT INTO ModeloVehiculos VALUES (88, 9, 'Diesel')
INSERT INTO ModeloVehiculos VALUES (89, 10, 'Brooklands')
INSERT INTO ModeloVehiculos VALUES (90, 10, 'Turbo')
INSERT INTO ModeloVehiculos VALUES (91, 10, 'Continental')
INSERT INTO ModeloVehiculos VALUES (92, 10, 'Azure')
INSERT INTO ModeloVehiculos VALUES (93, 10, 'Arnage')
INSERT INTO ModeloVehiculos VALUES (94, 10, 'Continental Gt')
INSERT INTO ModeloVehiculos VALUES (95, 10, 'Continental Flying Spur')
INSERT INTO ModeloVehiculos VALUES (96, 10, 'Turbo R')
INSERT INTO ModeloVehiculos VALUES (97, 10, 'Mulsanne')
INSERT INTO ModeloVehiculos VALUES (98, 10, 'Eight')
INSERT INTO ModeloVehiculos VALUES (99, 10, 'Continental Gtc')
INSERT INTO ModeloVehiculos VALUES (100, 10, 'Continental Supersports')
INSERT INTO ModeloVehiculos VALUES (101, 11, 'Freeclimber Diesel')
INSERT INTO ModeloVehiculos VALUES (102, 12, 'Serie 3')
INSERT INTO ModeloVehiculos VALUES (103, 12, 'Serie 5')
INSERT INTO ModeloVehiculos VALUES (104, 12, 'Compact')
INSERT INTO ModeloVehiculos VALUES (105, 12, 'Serie 7')
INSERT INTO ModeloVehiculos VALUES (106, 12, 'Serie 8')
INSERT INTO ModeloVehiculos VALUES (107, 12, 'Z3')
INSERT INTO ModeloVehiculos VALUES (108, 12, 'Z4')
INSERT INTO ModeloVehiculos VALUES (109, 12, 'Z8')
INSERT INTO ModeloVehiculos VALUES (110, 12, 'X5')
INSERT INTO ModeloVehiculos VALUES (111, 12, 'Serie 6')
INSERT INTO ModeloVehiculos VALUES (112, 12, 'X3')
INSERT INTO ModeloVehiculos VALUES (113, 12, 'Serie 1')
INSERT INTO ModeloVehiculos VALUES (114, 12, 'Z1')
INSERT INTO ModeloVehiculos VALUES (115, 12, 'X6')
INSERT INTO ModeloVehiculos VALUES (116, 12, 'X1')
INSERT INTO ModeloVehiculos VALUES (117, 13, 'Seville')
INSERT INTO ModeloVehiculos VALUES (118, 13, 'Sts')
INSERT INTO ModeloVehiculos VALUES (119, 13, 'El Dorado')
INSERT INTO ModeloVehiculos VALUES (120, 13, 'Cts')
INSERT INTO ModeloVehiculos VALUES (121, 13, 'Xlr')
INSERT INTO ModeloVehiculos VALUES (122, 13, 'Srx')
INSERT INTO ModeloVehiculos VALUES (123, 13, 'Escalade')
INSERT INTO ModeloVehiculos VALUES (124, 13, 'Bls')
INSERT INTO ModeloVehiculos VALUES (125, 14, 'Corvette')
INSERT INTO ModeloVehiculos VALUES (126, 14, 'Blazer')
INSERT INTO ModeloVehiculos VALUES (127, 14, 'Astro')
INSERT INTO ModeloVehiculos VALUES (128, 14, 'Nubira')
INSERT INTO ModeloVehiculos VALUES (129, 14, 'Evanda')
INSERT INTO ModeloVehiculos VALUES (130, 14, 'Trans Sport')
INSERT INTO ModeloVehiculos VALUES (131, 14, 'Camaro')
INSERT INTO ModeloVehiculos VALUES (132, 14, 'Matiz')
INSERT INTO ModeloVehiculos VALUES (133, 14, 'Alero')
INSERT INTO ModeloVehiculos VALUES (134, 14, 'Tahoe')
INSERT INTO ModeloVehiculos VALUES (135, 14, 'Tacuma')
INSERT INTO ModeloVehiculos VALUES (136, 14, 'Trailblazer')
INSERT INTO ModeloVehiculos VALUES (137, 14, 'Kalos')
INSERT INTO ModeloVehiculos VALUES (138, 14, 'Aveo')
INSERT INTO ModeloVehiculos VALUES (139, 14, 'Lacetti')
INSERT INTO ModeloVehiculos VALUES (140, 14, 'Epica')
INSERT INTO ModeloVehiculos VALUES (141, 14, 'Captiva')
INSERT INTO ModeloVehiculos VALUES (142, 14, 'Hhr')
INSERT INTO ModeloVehiculos VALUES (143, 14, 'Cruze')
INSERT INTO ModeloVehiculos VALUES (144, 14, 'Spark')
INSERT INTO ModeloVehiculos VALUES (145, 14, 'Orlando')
INSERT INTO ModeloVehiculos VALUES (146, 14, 'Volt')
INSERT INTO ModeloVehiculos VALUES (147, 14, 'Malibu')
INSERT INTO ModeloVehiculos VALUES (148, 15, 'Vision')
INSERT INTO ModeloVehiculos VALUES (149, 15, '300m')
INSERT INTO ModeloVehiculos VALUES (150, 15, 'Grand Voyager')
INSERT INTO ModeloVehiculos VALUES (151, 15, 'Viper')
INSERT INTO ModeloVehiculos VALUES (152, 15, 'Neon')
INSERT INTO ModeloVehiculos VALUES (153, 15, 'Voyager')
INSERT INTO ModeloVehiculos VALUES (154, 15, 'Stratus')
INSERT INTO ModeloVehiculos VALUES (155, 15, 'Sebring')
INSERT INTO ModeloVehiculos VALUES (156, 15, 'Sebring 200c')
INSERT INTO ModeloVehiculos VALUES (157, 15, 'New Yorker')
INSERT INTO ModeloVehiculos VALUES (158, 15, 'Pt Cruiser')
INSERT INTO ModeloVehiculos VALUES (159, 15, 'Crossfire')
INSERT INTO ModeloVehiculos VALUES (160, 15, '300c')
INSERT INTO ModeloVehiculos VALUES (161, 15, 'Le Baron')
INSERT INTO ModeloVehiculos VALUES (162, 15, 'Saratoga')
INSERT INTO ModeloVehiculos VALUES (163, 16, 'Xantia')
INSERT INTO ModeloVehiculos VALUES (164, 16, 'Xm')
INSERT INTO ModeloVehiculos VALUES (165, 16, 'Ax')
INSERT INTO ModeloVehiculos VALUES (166, 16, 'Zx')
INSERT INTO ModeloVehiculos VALUES (167, 16, 'Evasion')
INSERT INTO ModeloVehiculos VALUES (168, 16, 'C8')
INSERT INTO ModeloVehiculos VALUES (169, 16, 'Saxo')
INSERT INTO ModeloVehiculos VALUES (170, 16, 'C2')
INSERT INTO ModeloVehiculos VALUES (171, 16, 'Xsara')
INSERT INTO ModeloVehiculos VALUES (172, 16, 'C4')
INSERT INTO ModeloVehiculos VALUES (173, 16, 'Xsara Picasso')
INSERT INTO ModeloVehiculos VALUES (174, 16, 'C5')
INSERT INTO ModeloVehiculos VALUES (175, 16, 'C3')
INSERT INTO ModeloVehiculos VALUES (176, 16, 'C3 Pluriel')
INSERT INTO ModeloVehiculos VALUES (177, 16, 'C1')
INSERT INTO ModeloVehiculos VALUES (178, 16, 'C6')
INSERT INTO ModeloVehiculos VALUES (179, 16, 'Grand C4 Picasso')
INSERT INTO ModeloVehiculos VALUES (180, 16, 'C4 Picasso')
INSERT INTO ModeloVehiculos VALUES (181, 16, 'Ccrosser')
INSERT INTO ModeloVehiculos VALUES (182, 16, 'C15')
INSERT INTO ModeloVehiculos VALUES (183, 16, 'Jumper')
INSERT INTO ModeloVehiculos VALUES (184, 16, 'Jumpy')
INSERT INTO ModeloVehiculos VALUES (185, 16, 'Berlingo')
INSERT INTO ModeloVehiculos VALUES (186, 16, 'Bx')
INSERT INTO ModeloVehiculos VALUES (187, 16, 'C25')
INSERT INTO ModeloVehiculos VALUES (188, 16, 'Cx')
INSERT INTO ModeloVehiculos VALUES (189, 16, 'Gsa')
INSERT INTO ModeloVehiculos VALUES (190, 16, 'Visa')
INSERT INTO ModeloVehiculos VALUES (191, 16, 'Lna')
INSERT INTO ModeloVehiculos VALUES (192, 16, '2cv')
INSERT INTO ModeloVehiculos VALUES (193, 16, 'Nemo')
INSERT INTO ModeloVehiculos VALUES (194, 16, 'C4 Sedan')
INSERT INTO ModeloVehiculos VALUES (195, 16, 'Berlingo First')
INSERT INTO ModeloVehiculos VALUES (196, 16, 'C3 Picasso')
INSERT INTO ModeloVehiculos VALUES (197, 16, 'Ds3')
INSERT INTO ModeloVehiculos VALUES (198, 16, 'Czero')
INSERT INTO ModeloVehiculos VALUES (199, 16, 'Ds4')
INSERT INTO ModeloVehiculos VALUES (200, 16, 'Ds5')
INSERT INTO ModeloVehiculos VALUES (201, 16, 'C4 Aircross')
INSERT INTO ModeloVehiculos VALUES (202, 16, 'Celysee')
INSERT INTO ModeloVehiculos VALUES (203, 17, 'Corvette')
INSERT INTO ModeloVehiculos VALUES (204, 18, 'Contac')
INSERT INTO ModeloVehiculos VALUES (205, 18, 'Logan')
INSERT INTO ModeloVehiculos VALUES (206, 18, 'Sandero')
INSERT INTO ModeloVehiculos VALUES (207, 18, 'Duster')
INSERT INTO ModeloVehiculos VALUES (208, 18, 'Lodgy')
INSERT INTO ModeloVehiculos VALUES (209, 19, 'Nexia')
INSERT INTO ModeloVehiculos VALUES (210, 19, 'Aranos')
INSERT INTO ModeloVehiculos VALUES (211, 19, 'Lanos')
INSERT INTO ModeloVehiculos VALUES (212, 19, 'Nubira')
INSERT INTO ModeloVehiculos VALUES (213, 19, 'Compact')
INSERT INTO ModeloVehiculos VALUES (214, 19, 'Nubira Compact')
INSERT INTO ModeloVehiculos VALUES (215, 19, 'Leganza')
INSERT INTO ModeloVehiculos VALUES (216, 19, 'Evanda')
INSERT INTO ModeloVehiculos VALUES (217, 19, 'Matiz')
INSERT INTO ModeloVehiculos VALUES (218, 19, 'Tacuma')
INSERT INTO ModeloVehiculos VALUES (219, 19, 'Kalos')
INSERT INTO ModeloVehiculos VALUES (220, 19, 'Lacetti')
INSERT INTO ModeloVehiculos VALUES (221, 21, 'Applause')
INSERT INTO ModeloVehiculos VALUES (222, 21, 'Charade')
INSERT INTO ModeloVehiculos VALUES (223, 21, 'Rocky')
INSERT INTO ModeloVehiculos VALUES (224, 21, 'Feroza')
INSERT INTO ModeloVehiculos VALUES (225, 21, 'Terios')
INSERT INTO ModeloVehiculos VALUES (226, 21, 'Sirion')
INSERT INTO ModeloVehiculos VALUES (227, 22, 'Serie Xj')
INSERT INTO ModeloVehiculos VALUES (228, 22, 'Xj')
INSERT INTO ModeloVehiculos VALUES (229, 22, 'Double Six')
INSERT INTO ModeloVehiculos VALUES (230, 22, 'Six')
INSERT INTO ModeloVehiculos VALUES (231, 22, 'Series Iii')
INSERT INTO ModeloVehiculos VALUES (232, 23, 'Viper')
INSERT INTO ModeloVehiculos VALUES (233, 23, 'Caliber')
INSERT INTO ModeloVehiculos VALUES (234, 23, 'Nitro')
INSERT INTO ModeloVehiculos VALUES (235, 23, 'Avenger')
INSERT INTO ModeloVehiculos VALUES (236, 23, 'Journey')
INSERT INTO ModeloVehiculos VALUES (237, 24, 'F355')
INSERT INTO ModeloVehiculos VALUES (238, 24, '360')
INSERT INTO ModeloVehiculos VALUES (239, 24, 'F430')
INSERT INTO ModeloVehiculos VALUES (240, 24, 'F512 M')
INSERT INTO ModeloVehiculos VALUES (241, 24, '550 Maranello')
INSERT INTO ModeloVehiculos VALUES (242, 24, '575m Maranello')
INSERT INTO ModeloVehiculos VALUES (243, 24, '599')
INSERT INTO ModeloVehiculos VALUES (244, 24, '456')
INSERT INTO ModeloVehiculos VALUES (245, 24, '456m')
INSERT INTO ModeloVehiculos VALUES (246, 24, '612')
INSERT INTO ModeloVehiculos VALUES (247, 24, 'F50')
INSERT INTO ModeloVehiculos VALUES (248, 24, 'Enzo')
INSERT INTO ModeloVehiculos VALUES (249, 24, 'Superamerica')
INSERT INTO ModeloVehiculos VALUES (250, 24, '430')
INSERT INTO ModeloVehiculos VALUES (251, 24, '348')
INSERT INTO ModeloVehiculos VALUES (252, 24, 'Testarossa')
INSERT INTO ModeloVehiculos VALUES (253, 24, '512')
INSERT INTO ModeloVehiculos VALUES (254, 24, '355')
INSERT INTO ModeloVehiculos VALUES (255, 24, 'F40')
INSERT INTO ModeloVehiculos VALUES (256, 24, '412')
INSERT INTO ModeloVehiculos VALUES (257, 24, 'Mondial')
INSERT INTO ModeloVehiculos VALUES (258, 24, '328')
INSERT INTO ModeloVehiculos VALUES (259, 24, 'California')
INSERT INTO ModeloVehiculos VALUES (260, 24, '458')
INSERT INTO ModeloVehiculos VALUES (261, 24, 'Ff')
INSERT INTO ModeloVehiculos VALUES (262, 25, 'Croma')
INSERT INTO ModeloVehiculos VALUES (263, 25, 'Cinquecento')
INSERT INTO ModeloVehiculos VALUES (264, 25, 'Seicento')
INSERT INTO ModeloVehiculos VALUES (265, 25, 'Punto')
INSERT INTO ModeloVehiculos VALUES (266, 25, 'Grande Punto')
INSERT INTO ModeloVehiculos VALUES (267, 25, 'Panda')
INSERT INTO ModeloVehiculos VALUES (268, 25, 'Tipo')
INSERT INTO ModeloVehiculos VALUES (269, 25, 'Coupe')
INSERT INTO ModeloVehiculos VALUES (270, 25, 'Uno')
INSERT INTO ModeloVehiculos VALUES (271, 25, 'Ulysse')
INSERT INTO ModeloVehiculos VALUES (272, 25, 'Tempra')
INSERT INTO ModeloVehiculos VALUES (273, 25, 'Marea')
INSERT INTO ModeloVehiculos VALUES (274, 25, 'Barchetta')
INSERT INTO ModeloVehiculos VALUES (275, 25, 'Bravo')
INSERT INTO ModeloVehiculos VALUES (276, 25, 'Stilo')
INSERT INTO ModeloVehiculos VALUES (277, 25, 'Brava')
INSERT INTO ModeloVehiculos VALUES (278, 25, 'Palio Weekend')
INSERT INTO ModeloVehiculos VALUES (279, 25, '600')
INSERT INTO ModeloVehiculos VALUES (280, 25, 'Multipla')
INSERT INTO ModeloVehiculos VALUES (281, 25, 'Idea')
INSERT INTO ModeloVehiculos VALUES (282, 25, 'Sedici')
INSERT INTO ModeloVehiculos VALUES (283, 25, 'Linea')
INSERT INTO ModeloVehiculos VALUES (284, 25, '500')
INSERT INTO ModeloVehiculos VALUES (285, 25, 'Fiorino')
INSERT INTO ModeloVehiculos VALUES (286, 25, 'Ducato')
INSERT INTO ModeloVehiculos VALUES (287, 25, 'Doblo Cargo')
INSERT INTO ModeloVehiculos VALUES (288, 25, 'Doblo')
INSERT INTO ModeloVehiculos VALUES (289, 25, 'Strada')
INSERT INTO ModeloVehiculos VALUES (290, 25, 'Regata')
INSERT INTO ModeloVehiculos VALUES (291, 25, 'Talento')
INSERT INTO ModeloVehiculos VALUES (292, 25, 'Argenta')
INSERT INTO ModeloVehiculos VALUES (293, 25, 'Ritmo')
INSERT INTO ModeloVehiculos VALUES (294, 25, 'Punto Classic')
INSERT INTO ModeloVehiculos VALUES (295, 25, 'Qubo')
INSERT INTO ModeloVehiculos VALUES (296, 25, 'Punto Evo')
INSERT INTO ModeloVehiculos VALUES (297, 25, '500c')
INSERT INTO ModeloVehiculos VALUES (298, 25, 'Freemont')
INSERT INTO ModeloVehiculos VALUES (299, 25, 'Panda Classic')
INSERT INTO ModeloVehiculos VALUES (300, 25, '500l')
INSERT INTO ModeloVehiculos VALUES (301, 26, 'Maverick')
INSERT INTO ModeloVehiculos VALUES (302, 26, 'Escort')
INSERT INTO ModeloVehiculos VALUES (303, 26, 'Focus')
INSERT INTO ModeloVehiculos VALUES (304, 26, 'Mondeo')
INSERT INTO ModeloVehiculos VALUES (305, 26, 'Scorpio')
INSERT INTO ModeloVehiculos VALUES (306, 26, 'Fiesta')
INSERT INTO ModeloVehiculos VALUES (307, 26, 'Probe')
INSERT INTO ModeloVehiculos VALUES (308, 26, 'Explorer')
INSERT INTO ModeloVehiculos VALUES (309, 26, 'Galaxy')
INSERT INTO ModeloVehiculos VALUES (310, 26, 'Ka')
INSERT INTO ModeloVehiculos VALUES (311, 26, 'Puma')
INSERT INTO ModeloVehiculos VALUES (312, 26, 'Cougar')
INSERT INTO ModeloVehiculos VALUES (313, 26, 'Focus Cmax')
INSERT INTO ModeloVehiculos VALUES (314, 26, 'Fusion')
INSERT INTO ModeloVehiculos VALUES (315, 26, 'Streetka')
INSERT INTO ModeloVehiculos VALUES (316, 26, 'Cmax')
INSERT INTO ModeloVehiculos VALUES (317, 26, 'Smax')
INSERT INTO ModeloVehiculos VALUES (318, 26, 'Transit')
INSERT INTO ModeloVehiculos VALUES (319, 26, 'Courier')
INSERT INTO ModeloVehiculos VALUES (320, 26, 'Ranger')
INSERT INTO ModeloVehiculos VALUES (321, 26, 'Sierra')
INSERT INTO ModeloVehiculos VALUES (322, 26, 'Orion')
INSERT INTO ModeloVehiculos VALUES (323, 26, 'Pick Up')
INSERT INTO ModeloVehiculos VALUES (324, 26, 'Capri')
INSERT INTO ModeloVehiculos VALUES (325, 26, 'Granada')
INSERT INTO ModeloVehiculos VALUES (326, 26, 'Kuga')
INSERT INTO ModeloVehiculos VALUES (327, 26, 'Grand Cmax')
INSERT INTO ModeloVehiculos VALUES (328, 26, 'Bmax')
INSERT INTO ModeloVehiculos VALUES (329, 26, 'Tourneo Custom')
INSERT INTO ModeloVehiculos VALUES (330, 27, 'Exceed')
INSERT INTO ModeloVehiculos VALUES (331, 27, 'Santamo')
INSERT INTO ModeloVehiculos VALUES (332, 27, 'Super Exceed')
INSERT INTO ModeloVehiculos VALUES (333, 29, 'Accord')
INSERT INTO ModeloVehiculos VALUES (334, 29, 'Civic')
INSERT INTO ModeloVehiculos VALUES (335, 29, 'Crx')
INSERT INTO ModeloVehiculos VALUES (336, 29, 'Prelude')
INSERT INTO ModeloVehiculos VALUES (337, 29, 'Nsx')
INSERT INTO ModeloVehiculos VALUES (338, 29, 'Legend')
INSERT INTO ModeloVehiculos VALUES (339, 29, 'Crv')
INSERT INTO ModeloVehiculos VALUES (340, 29, 'Hrv')
INSERT INTO ModeloVehiculos VALUES (341, 29, 'Logo')
INSERT INTO ModeloVehiculos VALUES (342, 29, 'S2000')
INSERT INTO ModeloVehiculos VALUES (343, 29, 'Stream')
INSERT INTO ModeloVehiculos VALUES (344, 29, 'Jazz')
INSERT INTO ModeloVehiculos VALUES (345, 29, 'Frv')
INSERT INTO ModeloVehiculos VALUES (346, 29, 'Concerto')
INSERT INTO ModeloVehiculos VALUES (347, 29, 'Insight')
INSERT INTO ModeloVehiculos VALUES (348, 29, 'Crz')
INSERT INTO ModeloVehiculos VALUES (349, 30, 'H2')
INSERT INTO ModeloVehiculos VALUES (350, 30, 'H3')
INSERT INTO ModeloVehiculos VALUES (351, 30, 'H3t')
INSERT INTO ModeloVehiculos VALUES (352, 31, 'Lantra')
INSERT INTO ModeloVehiculos VALUES (353, 31, 'Sonata')
INSERT INTO ModeloVehiculos VALUES (354, 31, 'Elantra')
INSERT INTO ModeloVehiculos VALUES (355, 31, 'Accent')
INSERT INTO ModeloVehiculos VALUES (356, 31, 'Scoupe')
INSERT INTO ModeloVehiculos VALUES (357, 31, 'Coupe')
INSERT INTO ModeloVehiculos VALUES (358, 31, 'Atos')
INSERT INTO ModeloVehiculos VALUES (359, 31, 'H1')
INSERT INTO ModeloVehiculos VALUES (360, 31, 'Atos Prime')
INSERT INTO ModeloVehiculos VALUES (361, 31, 'Xg')
INSERT INTO ModeloVehiculos VALUES (362, 31, 'Trajet')
INSERT INTO ModeloVehiculos VALUES (363, 31, 'Santa Fe')
INSERT INTO ModeloVehiculos VALUES (364, 31, 'Terracan')
INSERT INTO ModeloVehiculos VALUES (365, 31, 'Matrix')
INSERT INTO ModeloVehiculos VALUES (366, 31, 'Getz')
INSERT INTO ModeloVehiculos VALUES (367, 31, 'Tucson')
INSERT INTO ModeloVehiculos VALUES (368, 31, 'I30')
INSERT INTO ModeloVehiculos VALUES (369, 31, 'Pony')
INSERT INTO ModeloVehiculos VALUES (370, 31, 'Grandeur')
INSERT INTO ModeloVehiculos VALUES (371, 31, 'I10')
INSERT INTO ModeloVehiculos VALUES (372, 31, 'I800')
INSERT INTO ModeloVehiculos VALUES (373, 31, 'Sonata Fl')
INSERT INTO ModeloVehiculos VALUES (374, 31, 'Ix55')
INSERT INTO ModeloVehiculos VALUES (375, 31, 'I20')
INSERT INTO ModeloVehiculos VALUES (376, 31, 'Ix35')
INSERT INTO ModeloVehiculos VALUES (377, 31, 'Ix20')
INSERT INTO ModeloVehiculos VALUES (378, 31, 'Genesis')
INSERT INTO ModeloVehiculos VALUES (379, 31, 'I40')
INSERT INTO ModeloVehiculos VALUES (380, 31, 'Veloster')
INSERT INTO ModeloVehiculos VALUES (381, 32, 'G')
INSERT INTO ModeloVehiculos VALUES (382, 32, 'Ex')
INSERT INTO ModeloVehiculos VALUES (383, 32, 'Fx')
INSERT INTO ModeloVehiculos VALUES (384, 32, 'M')
INSERT INTO ModeloVehiculos VALUES (385, 33, 'Elba')
INSERT INTO ModeloVehiculos VALUES (386, 33, 'Minitre')
INSERT INTO ModeloVehiculos VALUES (387, 34, 'Trooper')
INSERT INTO ModeloVehiculos VALUES (388, 34, 'Pick Up')
INSERT INTO ModeloVehiculos VALUES (389, 34, 'D Max')
INSERT INTO ModeloVehiculos VALUES (390, 34, 'Rodeo')
INSERT INTO ModeloVehiculos VALUES (391, 34, 'Dmax')
INSERT INTO ModeloVehiculos VALUES (392, 34, 'Trroper')
INSERT INTO ModeloVehiculos VALUES (393, 35, 'Daily')
INSERT INTO ModeloVehiculos VALUES (394, 35, 'Massif')
INSERT INTO ModeloVehiculos VALUES (395, 36, 'Daily')
INSERT INTO ModeloVehiculos VALUES (396, 36, 'Duty')
INSERT INTO ModeloVehiculos VALUES (397, 37, 'Serie Xj')
INSERT INTO ModeloVehiculos VALUES (398, 37, 'Serie Xk')
INSERT INTO ModeloVehiculos VALUES (399, 37, 'Xj')
INSERT INTO ModeloVehiculos VALUES (400, 37, 'Stype')
INSERT INTO ModeloVehiculos VALUES (401, 37, 'Xf')
INSERT INTO ModeloVehiculos VALUES (402, 37, 'Xtype')
INSERT INTO ModeloVehiculos VALUES (403, 38, 'Wrangler')
INSERT INTO ModeloVehiculos VALUES (404, 38, 'Cherokee')
INSERT INTO ModeloVehiculos VALUES (405, 38, 'Grand Cherokee')
INSERT INTO ModeloVehiculos VALUES (406, 38, 'Commander')
INSERT INTO ModeloVehiculos VALUES (407, 38, 'Compass')
INSERT INTO ModeloVehiculos VALUES (408, 38, 'Wrangler Unlimited')
INSERT INTO ModeloVehiculos VALUES (409, 38, 'Patriot')
INSERT INTO ModeloVehiculos VALUES (410, 39, 'Sportage')
INSERT INTO ModeloVehiculos VALUES (411, 39, 'Sephia')
INSERT INTO ModeloVehiculos VALUES (412, 39, 'Sephia Ii')
INSERT INTO ModeloVehiculos VALUES (413, 39, 'Pride')
INSERT INTO ModeloVehiculos VALUES (414, 39, 'Clarus')
INSERT INTO ModeloVehiculos VALUES (415, 39, 'Shuma')
INSERT INTO ModeloVehiculos VALUES (416, 39, 'Carnival')
INSERT INTO ModeloVehiculos VALUES (417, 39, 'Joice')
INSERT INTO ModeloVehiculos VALUES (418, 39, 'Magentis')
INSERT INTO ModeloVehiculos VALUES (419, 39, 'Carens')
INSERT INTO ModeloVehiculos VALUES (420, 39, 'Rio')
INSERT INTO ModeloVehiculos VALUES (421, 39, 'Cerato')
INSERT INTO ModeloVehiculos VALUES (422, 39, 'Sorento')
INSERT INTO ModeloVehiculos VALUES (423, 39, 'Opirus')
INSERT INTO ModeloVehiculos VALUES (424, 39, 'Picanto')
INSERT INTO ModeloVehiculos VALUES (425, 39, 'Ceed')
INSERT INTO ModeloVehiculos VALUES (426, 39, 'Ceed Sporty Wagon')
INSERT INTO ModeloVehiculos VALUES (427, 39, 'Proceed')
INSERT INTO ModeloVehiculos VALUES (428, 39, 'K2500 Frontier')
INSERT INTO ModeloVehiculos VALUES (429, 39, 'K2500')
INSERT INTO ModeloVehiculos VALUES (430, 39, 'Soul')
INSERT INTO ModeloVehiculos VALUES (431, 39, 'Venga')
INSERT INTO ModeloVehiculos VALUES (432, 39, 'Optima')
INSERT INTO ModeloVehiculos VALUES (433, 39, 'Ceed Sportswagon')
INSERT INTO ModeloVehiculos VALUES (434, 40, 'Samara')
INSERT INTO ModeloVehiculos VALUES (435, 40, 'Niva')
INSERT INTO ModeloVehiculos VALUES (436, 40, 'Sagona')
INSERT INTO ModeloVehiculos VALUES (437, 40, 'Stawra 2110')
INSERT INTO ModeloVehiculos VALUES (438, 40, '214')
INSERT INTO ModeloVehiculos VALUES (439, 40, 'Kalina')
INSERT INTO ModeloVehiculos VALUES (440, 40, 'Serie 2100')
INSERT INTO ModeloVehiculos VALUES (441, 40, 'Priora')
INSERT INTO ModeloVehiculos VALUES (442, 41, 'Gallardo')
INSERT INTO ModeloVehiculos VALUES (443, 41, 'Murcielago')
INSERT INTO ModeloVehiculos VALUES (444, 41, 'Aventador')
INSERT INTO ModeloVehiculos VALUES (445, 42, 'Delta')
INSERT INTO ModeloVehiculos VALUES (446, 42, 'K')
INSERT INTO ModeloVehiculos VALUES (447, 42, 'Y10')
INSERT INTO ModeloVehiculos VALUES (448, 42, 'Dedra')
INSERT INTO ModeloVehiculos VALUES (449, 42, 'Lybra')
INSERT INTO ModeloVehiculos VALUES (450, 42, 'Z')
INSERT INTO ModeloVehiculos VALUES (451, 42, 'Y')
INSERT INTO ModeloVehiculos VALUES (452, 42, 'Ypsilon')
INSERT INTO ModeloVehiculos VALUES (453, 42, 'Thesis')
INSERT INTO ModeloVehiculos VALUES (454, 42, 'Phedra')
INSERT INTO ModeloVehiculos VALUES (455, 42, 'Musa')
INSERT INTO ModeloVehiculos VALUES (456, 42, 'Thema')
INSERT INTO ModeloVehiculos VALUES (457, 42, 'Zeta')
INSERT INTO ModeloVehiculos VALUES (458, 42, 'Kappa')
INSERT INTO ModeloVehiculos VALUES (459, 42, 'Trevi')
INSERT INTO ModeloVehiculos VALUES (460, 42, 'Prisma')
INSERT INTO ModeloVehiculos VALUES (461, 42, 'A112')
INSERT INTO ModeloVehiculos VALUES (462, 42, 'Ypsilon Elefantino')
INSERT INTO ModeloVehiculos VALUES (463, 42, 'Voyager')
INSERT INTO ModeloVehiculos VALUES (464, 43, 'Range Rover')
INSERT INTO ModeloVehiculos VALUES (465, 43, 'Defender')
INSERT INTO ModeloVehiculos VALUES (466, 43, 'Discovery')
INSERT INTO ModeloVehiculos VALUES (467, 43, 'Freelander')
INSERT INTO ModeloVehiculos VALUES (468, 43, 'Range Rover Sport')
INSERT INTO ModeloVehiculos VALUES (469, 43, 'Discovery 4')
INSERT INTO ModeloVehiculos VALUES (470, 43, 'Range Rover Evoque')
INSERT INTO ModeloVehiculos VALUES (471, 44, 'Maxus')
INSERT INTO ModeloVehiculos VALUES (472, 45, 'Ls400')
INSERT INTO ModeloVehiculos VALUES (473, 45, 'Ls430')
INSERT INTO ModeloVehiculos VALUES (474, 45, 'Gs300')
INSERT INTO ModeloVehiculos VALUES (475, 45, 'Is200')
INSERT INTO ModeloVehiculos VALUES (476, 45, 'Rx300')
INSERT INTO ModeloVehiculos VALUES (477, 45, 'Gs430')
INSERT INTO ModeloVehiculos VALUES (478, 45, 'Gs460')
INSERT INTO ModeloVehiculos VALUES (479, 45, 'Sc430')
INSERT INTO ModeloVehiculos VALUES (480, 45, 'Is300')
INSERT INTO ModeloVehiculos VALUES (481, 45, 'Is250')
INSERT INTO ModeloVehiculos VALUES (482, 45, 'Rx400h')
INSERT INTO ModeloVehiculos VALUES (483, 45, 'Is220d')
INSERT INTO ModeloVehiculos VALUES (484, 45, 'Rx350')
INSERT INTO ModeloVehiculos VALUES (485, 45, 'Gs450h')
INSERT INTO ModeloVehiculos VALUES (486, 45, 'Ls460')
INSERT INTO ModeloVehiculos VALUES (487, 45, 'Ls600h')
INSERT INTO ModeloVehiculos VALUES (488, 45, 'Ls')
INSERT INTO ModeloVehiculos VALUES (489, 45, 'Gs')
INSERT INTO ModeloVehiculos VALUES (490, 45, 'Is')
INSERT INTO ModeloVehiculos VALUES (491, 45, 'Sc')
INSERT INTO ModeloVehiculos VALUES (492, 45, 'Rx')
INSERT INTO ModeloVehiculos VALUES (493, 45, 'Ct')
INSERT INTO ModeloVehiculos VALUES (494, 46, 'Elise')
INSERT INTO ModeloVehiculos VALUES (495, 46, 'Exige')
INSERT INTO ModeloVehiculos VALUES (496, 47, 'Bolero Pickup')
INSERT INTO ModeloVehiculos VALUES (497, 47, 'Goa Pickup')
INSERT INTO ModeloVehiculos VALUES (498, 47, 'Goa')
INSERT INTO ModeloVehiculos VALUES (499, 47, 'Cj')
INSERT INTO ModeloVehiculos VALUES (500, 47, 'Pikup')
INSERT INTO ModeloVehiculos VALUES (501, 47, 'Thar')
INSERT INTO ModeloVehiculos VALUES (502, 48, 'Ghibli')
INSERT INTO ModeloVehiculos VALUES (503, 48, 'Shamal')
INSERT INTO ModeloVehiculos VALUES (504, 48, 'Quattroporte')
INSERT INTO ModeloVehiculos VALUES (505, 48, '3200 Gt')
INSERT INTO ModeloVehiculos VALUES (506, 48, 'Coupe')
INSERT INTO ModeloVehiculos VALUES (507, 48, 'Spyder')
INSERT INTO ModeloVehiculos VALUES (508, 48, 'Gransport')
INSERT INTO ModeloVehiculos VALUES (509, 48, 'Granturismo')
INSERT INTO ModeloVehiculos VALUES (510, 48, '430')
INSERT INTO ModeloVehiculos VALUES (511, 48, 'Biturbo')
INSERT INTO ModeloVehiculos VALUES (512, 48, '228')
INSERT INTO ModeloVehiculos VALUES (513, 48, '224')
INSERT INTO ModeloVehiculos VALUES (514, 48, 'Grancabrio')
INSERT INTO ModeloVehiculos VALUES (515, 49, 'Maybach')
INSERT INTO ModeloVehiculos VALUES (516, 50, 'Xedos 6')
INSERT INTO ModeloVehiculos VALUES (517, 50, '626')
INSERT INTO ModeloVehiculos VALUES (518, 50, '121')
INSERT INTO ModeloVehiculos VALUES (519, 50, 'Xedos 9')
INSERT INTO ModeloVehiculos VALUES (520, 50, '323')
INSERT INTO ModeloVehiculos VALUES (521, 50, 'Mx3')
INSERT INTO ModeloVehiculos VALUES (522, 50, 'Rx7')
INSERT INTO ModeloVehiculos VALUES (523, 50, 'Mx5')
INSERT INTO ModeloVehiculos VALUES (524, 50, 'Mazda3')
INSERT INTO ModeloVehiculos VALUES (525, 50, 'Mpv')
INSERT INTO ModeloVehiculos VALUES (526, 50, 'Demio')
INSERT INTO ModeloVehiculos VALUES (527, 50, 'Premacy')
INSERT INTO ModeloVehiculos VALUES (528, 50, 'Tribute')
INSERT INTO ModeloVehiculos VALUES (529, 50, 'Mazda6')
INSERT INTO ModeloVehiculos VALUES (530, 50, 'Mazda2')
INSERT INTO ModeloVehiculos VALUES (531, 50, 'Rx8')
INSERT INTO ModeloVehiculos VALUES (532, 50, 'Mazda5')
INSERT INTO ModeloVehiculos VALUES (533, 50, 'Cx7')
INSERT INTO ModeloVehiculos VALUES (534, 50, 'Serie B')
INSERT INTO ModeloVehiculos VALUES (535, 50, 'B2500')
INSERT INTO ModeloVehiculos VALUES (536, 50, 'Bt50')
INSERT INTO ModeloVehiculos VALUES (537, 50, 'Mx6')
INSERT INTO ModeloVehiculos VALUES (538, 50, '929')
INSERT INTO ModeloVehiculos VALUES (539, 50, 'Cx5')
INSERT INTO ModeloVehiculos VALUES (540, 51, 'Clase C')
INSERT INTO ModeloVehiculos VALUES (541, 51, 'Clase E')
INSERT INTO ModeloVehiculos VALUES (542, 51, 'Clase Sl')
INSERT INTO ModeloVehiculos VALUES (543, 51, 'Clase S')
INSERT INTO ModeloVehiculos VALUES (544, 51, 'Clase Cl')
INSERT INTO ModeloVehiculos VALUES (545, 51, 'Clase G')
INSERT INTO ModeloVehiculos VALUES (546, 51, 'Clase Slk')
INSERT INTO ModeloVehiculos VALUES (547, 51, 'Clase V')
INSERT INTO ModeloVehiculos VALUES (548, 51, 'Viano')
INSERT INTO ModeloVehiculos VALUES (549, 51, 'Clase Clk')
INSERT INTO ModeloVehiculos VALUES (550, 51, 'Clase A')
INSERT INTO ModeloVehiculos VALUES (551, 51, 'Clase M')
INSERT INTO ModeloVehiculos VALUES (552, 51, 'Vaneo')
INSERT INTO ModeloVehiculos VALUES (553, 51, 'Slklasse')
INSERT INTO ModeloVehiculos VALUES (554, 51, 'Slr Mclaren')
INSERT INTO ModeloVehiculos VALUES (555, 51, 'Clase Cls')
INSERT INTO ModeloVehiculos VALUES (556, 51, 'Clase R')
INSERT INTO ModeloVehiculos VALUES (557, 51, 'Clase Gl')
INSERT INTO ModeloVehiculos VALUES (558, 51, 'Clase B')
INSERT INTO ModeloVehiculos VALUES (559, 51, '100d')
INSERT INTO ModeloVehiculos VALUES (560, 51, '140d')
INSERT INTO ModeloVehiculos VALUES (561, 51, '180d')
INSERT INTO ModeloVehiculos VALUES (562, 51, 'Sprinter')
INSERT INTO ModeloVehiculos VALUES (563, 51, 'Vito')
INSERT INTO ModeloVehiculos VALUES (564, 51, 'Transporter')
INSERT INTO ModeloVehiculos VALUES (565, 51, '280')
INSERT INTO ModeloVehiculos VALUES (566, 51, '220')
INSERT INTO ModeloVehiculos VALUES (567, 51, '200')
INSERT INTO ModeloVehiculos VALUES (568, 51, '190')
INSERT INTO ModeloVehiculos VALUES (569, 51, '600')
INSERT INTO ModeloVehiculos VALUES (570, 51, '400')
INSERT INTO ModeloVehiculos VALUES (571, 51, 'Clase Sl R129')
INSERT INTO ModeloVehiculos VALUES (572, 51, '300')
INSERT INTO ModeloVehiculos VALUES (573, 51, '500')
INSERT INTO ModeloVehiculos VALUES (574, 51, '420')
INSERT INTO ModeloVehiculos VALUES (575, 51, '260')
INSERT INTO ModeloVehiculos VALUES (576, 51, '230')
INSERT INTO ModeloVehiculos VALUES (577, 51, 'Clase Clc')
INSERT INTO ModeloVehiculos VALUES (578, 51, 'Clase Glk')
INSERT INTO ModeloVehiculos VALUES (579, 51, 'Sls Amg')
INSERT INTO ModeloVehiculos VALUES (580, 52, 'Mgf')
INSERT INTO ModeloVehiculos VALUES (581, 52, 'Tf')
INSERT INTO ModeloVehiculos VALUES (582, 52, 'Zr')
INSERT INTO ModeloVehiculos VALUES (583, 52, 'Zs')
INSERT INTO ModeloVehiculos VALUES (584, 52, 'Zt')
INSERT INTO ModeloVehiculos VALUES (585, 52, 'Ztt')
INSERT INTO ModeloVehiculos VALUES (586, 52, 'Mini')
INSERT INTO ModeloVehiculos VALUES (587, 52, 'Countryman')
INSERT INTO ModeloVehiculos VALUES (588, 52, 'Paceman')
INSERT INTO ModeloVehiculos VALUES (589, 54, 'Montero')
INSERT INTO ModeloVehiculos VALUES (590, 54, 'Galant')
INSERT INTO ModeloVehiculos VALUES (591, 54, 'Colt')
INSERT INTO ModeloVehiculos VALUES (592, 54, 'Space Wagon')
INSERT INTO ModeloVehiculos VALUES (593, 54, 'Space Runner')
INSERT INTO ModeloVehiculos VALUES (594, 54, 'Space Gear')
INSERT INTO ModeloVehiculos VALUES (595, 54, '3000 Gt')
INSERT INTO ModeloVehiculos VALUES (596, 54, 'Carisma')
INSERT INTO ModeloVehiculos VALUES (597, 54, 'Eclipse')
INSERT INTO ModeloVehiculos VALUES (598, 54, 'Space Star')
INSERT INTO ModeloVehiculos VALUES (599, 54, 'Montero Sport')
INSERT INTO ModeloVehiculos VALUES (600, 54, 'Montero Io')
INSERT INTO ModeloVehiculos VALUES (601, 54, 'Outlander')
INSERT INTO ModeloVehiculos VALUES (602, 54, 'Lancer')
INSERT INTO ModeloVehiculos VALUES (603, 54, 'Grandis')
INSERT INTO ModeloVehiculos VALUES (604, 54, 'L200')
INSERT INTO ModeloVehiculos VALUES (605, 54, 'Canter')
INSERT INTO ModeloVehiculos VALUES (606, 54, '300 Gt')
INSERT INTO ModeloVehiculos VALUES (607, 54, 'Asx')
INSERT INTO ModeloVehiculos VALUES (608, 54, 'Imiev')
INSERT INTO ModeloVehiculos VALUES (609, 55, '44')
INSERT INTO ModeloVehiculos VALUES (610, 55, 'Plus 8')
INSERT INTO ModeloVehiculos VALUES (611, 55, 'Aero 8')
INSERT INTO ModeloVehiculos VALUES (612, 55, 'V6')
INSERT INTO ModeloVehiculos VALUES (613, 55, 'Roadster')
INSERT INTO ModeloVehiculos VALUES (614, 55, '4')
INSERT INTO ModeloVehiculos VALUES (615, 55, 'Plus 4')
INSERT INTO ModeloVehiculos VALUES (616, 56, 'Terrano Ii')
INSERT INTO ModeloVehiculos VALUES (617, 56, 'Terrano')
INSERT INTO ModeloVehiculos VALUES (618, 56, 'Micra')
INSERT INTO ModeloVehiculos VALUES (619, 56, 'Sunny')
INSERT INTO ModeloVehiculos VALUES (620, 56, 'Primera')
INSERT INTO ModeloVehiculos VALUES (621, 56, 'Serena')
INSERT INTO ModeloVehiculos VALUES (622, 56, 'Patrol')
INSERT INTO ModeloVehiculos VALUES (623, 56, 'Maxima Qx')
INSERT INTO ModeloVehiculos VALUES (624, 56, '200 Sx')
INSERT INTO ModeloVehiculos VALUES (625, 56, '300 Zx')
INSERT INTO ModeloVehiculos VALUES (626, 56, 'Patrol Gr')
INSERT INTO ModeloVehiculos VALUES (627, 56, '100 Nx')
INSERT INTO ModeloVehiculos VALUES (628, 56, 'Almera')
INSERT INTO ModeloVehiculos VALUES (629, 56, 'Pathfinder')
INSERT INTO ModeloVehiculos VALUES (630, 56, 'Almera Tino')
INSERT INTO ModeloVehiculos VALUES (631, 56, 'Xtrail')
INSERT INTO ModeloVehiculos VALUES (632, 56, '350z')
INSERT INTO ModeloVehiculos VALUES (633, 56, 'Murano')
INSERT INTO ModeloVehiculos VALUES (634, 56, 'Note')
INSERT INTO ModeloVehiculos VALUES (635, 56, 'Qashqai')
INSERT INTO ModeloVehiculos VALUES (636, 56, 'Tiida')
INSERT INTO ModeloVehiculos VALUES (637, 56, 'Vanette')
INSERT INTO ModeloVehiculos VALUES (638, 56, 'Trade')
INSERT INTO ModeloVehiculos VALUES (639, 56, 'Vanette Cargo')
INSERT INTO ModeloVehiculos VALUES (640, 56, 'Pickup')
INSERT INTO ModeloVehiculos VALUES (641, 56, 'Navara')
INSERT INTO ModeloVehiculos VALUES (642, 56, 'Cabstar E')
INSERT INTO ModeloVehiculos VALUES (643, 56, 'Cabstar')
INSERT INTO ModeloVehiculos VALUES (644, 56, 'Maxima')
INSERT INTO ModeloVehiculos VALUES (645, 56, 'Camion')
INSERT INTO ModeloVehiculos VALUES (646, 56, 'Prairie')
INSERT INTO ModeloVehiculos VALUES (647, 56, 'Bluebird')
INSERT INTO ModeloVehiculos VALUES (648, 56, 'Np300 Pick Up')
INSERT INTO ModeloVehiculos VALUES (649, 56, 'Qashqai2')
INSERT INTO ModeloVehiculos VALUES (650, 56, 'Pixo')
INSERT INTO ModeloVehiculos VALUES (651, 56, 'Gtr')
INSERT INTO ModeloVehiculos VALUES (652, 56, '370z')
INSERT INTO ModeloVehiculos VALUES (653, 56, 'Cube')
INSERT INTO ModeloVehiculos VALUES (654, 56, 'Juke')
INSERT INTO ModeloVehiculos VALUES (655, 56, 'Leaf')
INSERT INTO ModeloVehiculos VALUES (656, 56, 'Evalia')
INSERT INTO ModeloVehiculos VALUES (657, 57, 'Astra')
INSERT INTO ModeloVehiculos VALUES (658, 57, 'Vectra')
INSERT INTO ModeloVehiculos VALUES (659, 57, 'Calibra')
INSERT INTO ModeloVehiculos VALUES (660, 57, 'Corsa')
INSERT INTO ModeloVehiculos VALUES (661, 57, 'Omega')
INSERT INTO ModeloVehiculos VALUES (662, 57, 'Frontera')
INSERT INTO ModeloVehiculos VALUES (663, 57, 'Tigra')
INSERT INTO ModeloVehiculos VALUES (664, 57, 'Monterey')
INSERT INTO ModeloVehiculos VALUES (665, 57, 'Sintra')
INSERT INTO ModeloVehiculos VALUES (666, 57, 'Zafira')
INSERT INTO ModeloVehiculos VALUES (667, 57, 'Agila')
INSERT INTO ModeloVehiculos VALUES (668, 57, 'Speedster')
INSERT INTO ModeloVehiculos VALUES (669, 57, 'Signum')
INSERT INTO ModeloVehiculos VALUES (670, 57, 'Meriva')
INSERT INTO ModeloVehiculos VALUES (671, 57, 'Antara')
INSERT INTO ModeloVehiculos VALUES (672, 57, 'Gt')
INSERT INTO ModeloVehiculos VALUES (673, 57, 'Combo')
INSERT INTO ModeloVehiculos VALUES (674, 57, 'Movano')
INSERT INTO ModeloVehiculos VALUES (675, 57, 'Vivaro')
INSERT INTO ModeloVehiculos VALUES (676, 57, 'Kadett')
INSERT INTO ModeloVehiculos VALUES (677, 57, 'Monza')
INSERT INTO ModeloVehiculos VALUES (678, 57, 'Senator')
INSERT INTO ModeloVehiculos VALUES (679, 57, 'Rekord')
INSERT INTO ModeloVehiculos VALUES (680, 57, 'Manta')
INSERT INTO ModeloVehiculos VALUES (681, 57, 'Ascona')
INSERT INTO ModeloVehiculos VALUES (682, 57, 'Insignia')
INSERT INTO ModeloVehiculos VALUES (683, 57, 'Zafira Tourer')
INSERT INTO ModeloVehiculos VALUES (684, 57, 'Ampera')
INSERT INTO ModeloVehiculos VALUES (685, 57, 'Mokka')
INSERT INTO ModeloVehiculos VALUES (686, 57, 'Adam')
INSERT INTO ModeloVehiculos VALUES (687, 58, '306')
INSERT INTO ModeloVehiculos VALUES (688, 58, '605')
INSERT INTO ModeloVehiculos VALUES (689, 58, '106')
INSERT INTO ModeloVehiculos VALUES (690, 58, '205')
INSERT INTO ModeloVehiculos VALUES (691, 58, '405')
INSERT INTO ModeloVehiculos VALUES (692, 58, '406')
INSERT INTO ModeloVehiculos VALUES (693, 58, '806')
INSERT INTO ModeloVehiculos VALUES (694, 58, '807')
INSERT INTO ModeloVehiculos VALUES (695, 58, '407')
INSERT INTO ModeloVehiculos VALUES (696, 58, '307')
INSERT INTO ModeloVehiculos VALUES (697, 58, '206')
INSERT INTO ModeloVehiculos VALUES (698, 58, '607')
INSERT INTO ModeloVehiculos VALUES (699, 58, '308')
INSERT INTO ModeloVehiculos VALUES (700, 58, '307 Sw')
INSERT INTO ModeloVehiculos VALUES (701, 58, '206 Sw')
INSERT INTO ModeloVehiculos VALUES (702, 58, '407 Sw')
INSERT INTO ModeloVehiculos VALUES (703, 58, '1007')
INSERT INTO ModeloVehiculos VALUES (704, 58, '107')
INSERT INTO ModeloVehiculos VALUES (705, 58, '207')
INSERT INTO ModeloVehiculos VALUES (706, 58, '4007')
INSERT INTO ModeloVehiculos VALUES (707, 58, 'Boxer')
INSERT INTO ModeloVehiculos VALUES (708, 58, 'Partner')
INSERT INTO ModeloVehiculos VALUES (709, 58, 'J5')
INSERT INTO ModeloVehiculos VALUES (710, 58, '604')
INSERT INTO ModeloVehiculos VALUES (711, 58, '505')
INSERT INTO ModeloVehiculos VALUES (712, 58, '309')
INSERT INTO ModeloVehiculos VALUES (713, 58, 'Bipper')
INSERT INTO ModeloVehiculos VALUES (714, 58, 'Partner Origin')
INSERT INTO ModeloVehiculos VALUES (715, 58, '3008')
INSERT INTO ModeloVehiculos VALUES (716, 58, '5008')
INSERT INTO ModeloVehiculos VALUES (717, 58, 'Rcz')
INSERT INTO ModeloVehiculos VALUES (718, 58, '508')
INSERT INTO ModeloVehiculos VALUES (719, 58, 'Ion')
INSERT INTO ModeloVehiculos VALUES (720, 58, '208')
INSERT INTO ModeloVehiculos VALUES (721, 58, '4008')
INSERT INTO ModeloVehiculos VALUES (722, 59, 'Trans Sport')
INSERT INTO ModeloVehiculos VALUES (723, 59, 'Firebird')
INSERT INTO ModeloVehiculos VALUES (724, 59, 'Trans Am')
INSERT INTO ModeloVehiculos VALUES (725, 60, '911')
INSERT INTO ModeloVehiculos VALUES (726, 60, 'Boxster')
INSERT INTO ModeloVehiculos VALUES (727, 60, 'Cayenne')
INSERT INTO ModeloVehiculos VALUES (728, 60, 'Carrera Gt')
INSERT INTO ModeloVehiculos VALUES (729, 60, 'Cayman')
INSERT INTO ModeloVehiculos VALUES (730, 60, '928')
INSERT INTO ModeloVehiculos VALUES (731, 60, '968')
INSERT INTO ModeloVehiculos VALUES (732, 60, '944')
INSERT INTO ModeloVehiculos VALUES (733, 60, '924')
INSERT INTO ModeloVehiculos VALUES (734, 60, 'Panamera')
INSERT INTO ModeloVehiculos VALUES (735, 60, '918')
INSERT INTO ModeloVehiculos VALUES (736, 61, 'Megane')
INSERT INTO ModeloVehiculos VALUES (737, 61, 'Safrane')
INSERT INTO ModeloVehiculos VALUES (738, 61, 'Laguna')
INSERT INTO ModeloVehiculos VALUES (739, 61, 'Clio')
INSERT INTO ModeloVehiculos VALUES (740, 61, 'Twingo')
INSERT INTO ModeloVehiculos VALUES (741, 61, 'Nevada')
INSERT INTO ModeloVehiculos VALUES (742, 61, 'Espace')
INSERT INTO ModeloVehiculos VALUES (743, 61, 'Spider')
INSERT INTO ModeloVehiculos VALUES (744, 61, 'Scenic')
INSERT INTO ModeloVehiculos VALUES (745, 61, 'Grand Espace')
INSERT INTO ModeloVehiculos VALUES (746, 61, 'Avantime')
INSERT INTO ModeloVehiculos VALUES (747, 61, 'Vel Satis')
INSERT INTO ModeloVehiculos VALUES (748, 61, 'Grand Scenic')
INSERT INTO ModeloVehiculos VALUES (749, 61, 'Clio Campus')
INSERT INTO ModeloVehiculos VALUES (750, 61, 'Modus')
INSERT INTO ModeloVehiculos VALUES (751, 61, 'Express')
INSERT INTO ModeloVehiculos VALUES (752, 61, 'Trafic')
INSERT INTO ModeloVehiculos VALUES (753, 61, 'Master')
INSERT INTO ModeloVehiculos VALUES (754, 61, 'Kangoo')
INSERT INTO ModeloVehiculos VALUES (755, 61, 'Mascott')
INSERT INTO ModeloVehiculos VALUES (756, 61, 'Master Propulsion')
INSERT INTO ModeloVehiculos VALUES (757, 61, 'Maxity')
INSERT INTO ModeloVehiculos VALUES (758, 61, 'R19')
INSERT INTO ModeloVehiculos VALUES (759, 61, 'R25')
INSERT INTO ModeloVehiculos VALUES (760, 61, 'R5')
INSERT INTO ModeloVehiculos VALUES (761, 61, 'R21')
INSERT INTO ModeloVehiculos VALUES (762, 61, 'R4')
INSERT INTO ModeloVehiculos VALUES (763, 61, 'Alpine')
INSERT INTO ModeloVehiculos VALUES (764, 61, 'Fuego')
INSERT INTO ModeloVehiculos VALUES (765, 61, 'R18')
INSERT INTO ModeloVehiculos VALUES (766, 61, 'R11')
INSERT INTO ModeloVehiculos VALUES (767, 61, 'R9')
INSERT INTO ModeloVehiculos VALUES (768, 61, 'R6')
INSERT INTO ModeloVehiculos VALUES (769, 61, 'Grand Modus')
INSERT INTO ModeloVehiculos VALUES (770, 61, 'Kangoo Combi')
INSERT INTO ModeloVehiculos VALUES (771, 61, 'Koleos')
INSERT INTO ModeloVehiculos VALUES (772, 61, 'Fluence')
INSERT INTO ModeloVehiculos VALUES (773, 61, 'Wind')
INSERT INTO ModeloVehiculos VALUES (774, 61, 'Latitude')
INSERT INTO ModeloVehiculos VALUES (775, 61, 'Grand Kangoo Combi')
INSERT INTO ModeloVehiculos VALUES (776, 62, 'Siver Dawn')
INSERT INTO ModeloVehiculos VALUES (777, 62, 'Silver Spur')
INSERT INTO ModeloVehiculos VALUES (778, 62, 'Park Ward')
INSERT INTO ModeloVehiculos VALUES (779, 62, 'Silver Seraph')
INSERT INTO ModeloVehiculos VALUES (780, 62, 'Corniche')
INSERT INTO ModeloVehiculos VALUES (781, 62, 'Phantom')
INSERT INTO ModeloVehiculos VALUES (782, 62, 'Touring')
INSERT INTO ModeloVehiculos VALUES (783, 62, 'Silvier')
INSERT INTO ModeloVehiculos VALUES (784, 63, '800')
INSERT INTO ModeloVehiculos VALUES (785, 63, '600')
INSERT INTO ModeloVehiculos VALUES (786, 63, '100')
INSERT INTO ModeloVehiculos VALUES (787, 63, '200')
INSERT INTO ModeloVehiculos VALUES (788, 63, 'Coupe')
INSERT INTO ModeloVehiculos VALUES (789, 63, '400')
INSERT INTO ModeloVehiculos VALUES (790, 63, '45')
INSERT INTO ModeloVehiculos VALUES (791, 63, 'Cabriolet')
INSERT INTO ModeloVehiculos VALUES (792, 63, '25')
INSERT INTO ModeloVehiculos VALUES (793, 63, 'Mini')
INSERT INTO ModeloVehiculos VALUES (794, 63, '75')
INSERT INTO ModeloVehiculos VALUES (795, 63, 'Streetwise')
INSERT INTO ModeloVehiculos VALUES (796, 63, 'Sd')
INSERT INTO ModeloVehiculos VALUES (797, 64, '900')
INSERT INTO ModeloVehiculos VALUES (798, 64, '93')
INSERT INTO ModeloVehiculos VALUES (799, 64, '9000')
INSERT INTO ModeloVehiculos VALUES (800, 64, '95')
INSERT INTO ModeloVehiculos VALUES (801, 64, '93x')
INSERT INTO ModeloVehiculos VALUES (802, 64, '94x')
INSERT INTO ModeloVehiculos VALUES (803, 65, '300')
INSERT INTO ModeloVehiculos VALUES (804, 65, '350')
INSERT INTO ModeloVehiculos VALUES (805, 65, 'Anibal')
INSERT INTO ModeloVehiculos VALUES (806, 65, 'Anibal Pick Up')
INSERT INTO ModeloVehiculos VALUES (807, 66, 'Ibiza')
INSERT INTO ModeloVehiculos VALUES (808, 66, 'Cordoba')
INSERT INTO ModeloVehiculos VALUES (809, 66, 'Toledo')
INSERT INTO ModeloVehiculos VALUES (810, 66, 'Marbella')
INSERT INTO ModeloVehiculos VALUES (811, 66, 'Alhambra')
INSERT INTO ModeloVehiculos VALUES (812, 66, 'Arosa')
INSERT INTO ModeloVehiculos VALUES (813, 66, 'Leon')
INSERT INTO ModeloVehiculos VALUES (814, 66, 'Altea')
INSERT INTO ModeloVehiculos VALUES (815, 66, 'Altea Xl')
INSERT INTO ModeloVehiculos VALUES (816, 66, 'Altea Freetrack')
INSERT INTO ModeloVehiculos VALUES (817, 66, 'Terra')
INSERT INTO ModeloVehiculos VALUES (818, 66, 'Inca')
INSERT INTO ModeloVehiculos VALUES (819, 66, 'Malaga')
INSERT INTO ModeloVehiculos VALUES (820, 66, 'Ronda')
INSERT INTO ModeloVehiculos VALUES (821, 66, 'Exeo')
INSERT INTO ModeloVehiculos VALUES (822, 66, 'Mii')
INSERT INTO ModeloVehiculos VALUES (823, 67, 'Felicia')
INSERT INTO ModeloVehiculos VALUES (824, 67, 'Forman')
INSERT INTO ModeloVehiculos VALUES (825, 67, 'Octavia')
INSERT INTO ModeloVehiculos VALUES (826, 67, 'Octavia Tour')
INSERT INTO ModeloVehiculos VALUES (827, 67, 'Fabia')
INSERT INTO ModeloVehiculos VALUES (828, 67, 'Superb')
INSERT INTO ModeloVehiculos VALUES (829, 67, 'Roomster')
INSERT INTO ModeloVehiculos VALUES (830, 67, 'Scout')
INSERT INTO ModeloVehiculos VALUES (831, 67, 'Pickup')
INSERT INTO ModeloVehiculos VALUES (832, 67, 'Favorit')
INSERT INTO ModeloVehiculos VALUES (833, 67, '130')
INSERT INTO ModeloVehiculos VALUES (834, 67, 'S')
INSERT INTO ModeloVehiculos VALUES (835, 67, 'Yeti')
INSERT INTO ModeloVehiculos VALUES (836, 67, 'Citigo')
INSERT INTO ModeloVehiculos VALUES (837, 67, 'Rapid')
INSERT INTO ModeloVehiculos VALUES (838, 68, 'Smart')
INSERT INTO ModeloVehiculos VALUES (839, 68, 'Citycoupe')
INSERT INTO ModeloVehiculos VALUES (840, 68, 'Fortwo')
INSERT INTO ModeloVehiculos VALUES (841, 68, 'Cabrio')
INSERT INTO ModeloVehiculos VALUES (842, 68, 'Crossblade')
INSERT INTO ModeloVehiculos VALUES (843, 68, 'Roadster')
INSERT INTO ModeloVehiculos VALUES (844, 68, 'Forfour')
INSERT INTO ModeloVehiculos VALUES (845, 69, 'Korando')
INSERT INTO ModeloVehiculos VALUES (846, 69, 'Family')
INSERT INTO ModeloVehiculos VALUES (847, 69, 'K4d')
INSERT INTO ModeloVehiculos VALUES (848, 69, 'Musso')
INSERT INTO ModeloVehiculos VALUES (849, 69, 'Korando Kj')
INSERT INTO ModeloVehiculos VALUES (850, 69, 'Rexton')
INSERT INTO ModeloVehiculos VALUES (851, 69, 'Rexton Ii')
INSERT INTO ModeloVehiculos VALUES (852, 69, 'Rodius')
INSERT INTO ModeloVehiculos VALUES (853, 69, 'Kyron')
INSERT INTO ModeloVehiculos VALUES (854, 69, 'Actyon')
INSERT INTO ModeloVehiculos VALUES (855, 69, 'Sports Pick Up')
INSERT INTO ModeloVehiculos VALUES (856, 69, 'Actyon Sports Pick Up')
INSERT INTO ModeloVehiculos VALUES (857, 69, 'Kodando')
INSERT INTO ModeloVehiculos VALUES (858, 70, 'Legacy')
INSERT INTO ModeloVehiculos VALUES (859, 70, 'Impreza')
INSERT INTO ModeloVehiculos VALUES (860, 70, 'Svx')
INSERT INTO ModeloVehiculos VALUES (861, 70, 'Justy')
INSERT INTO ModeloVehiculos VALUES (862, 70, 'Outback')
INSERT INTO ModeloVehiculos VALUES (863, 70, 'Forester')
INSERT INTO ModeloVehiculos VALUES (864, 70, 'G3x Justy')
INSERT INTO ModeloVehiculos VALUES (865, 70, 'B9 Tribeca')
INSERT INTO ModeloVehiculos VALUES (866, 70, 'Xt')
INSERT INTO ModeloVehiculos VALUES (867, 70, '1800')
INSERT INTO ModeloVehiculos VALUES (868, 70, 'Tribeca')
INSERT INTO ModeloVehiculos VALUES (869, 70, 'Wrx Sti')
INSERT INTO ModeloVehiculos VALUES (870, 70, 'Trezia')
INSERT INTO ModeloVehiculos VALUES (871, 70, 'Xv')
INSERT INTO ModeloVehiculos VALUES (872, 70, 'Brz')
INSERT INTO ModeloVehiculos VALUES (873, 71, 'Maruti')
INSERT INTO ModeloVehiculos VALUES (874, 71, 'Swift')
INSERT INTO ModeloVehiculos VALUES (875, 71, 'Vitara')
INSERT INTO ModeloVehiculos VALUES (876, 71, 'Baleno')
INSERT INTO ModeloVehiculos VALUES (877, 71, 'Samurai')
INSERT INTO ModeloVehiculos VALUES (878, 71, 'Alto')
INSERT INTO ModeloVehiculos VALUES (879, 71, 'Wagon R')
INSERT INTO ModeloVehiculos VALUES (880, 71, 'Jimny')
INSERT INTO ModeloVehiculos VALUES (881, 71, 'Grand Vitara')
INSERT INTO ModeloVehiculos VALUES (882, 71, 'Ignis')
INSERT INTO ModeloVehiculos VALUES (883, 71, 'Liana')
INSERT INTO ModeloVehiculos VALUES (884, 71, 'Grand Vitara Xl7')
INSERT INTO ModeloVehiculos VALUES (885, 71, 'Sx4')
INSERT INTO ModeloVehiculos VALUES (886, 71, 'Splash')
INSERT INTO ModeloVehiculos VALUES (887, 71, 'Kizashi')
INSERT INTO ModeloVehiculos VALUES (888, 72, 'Samba')
INSERT INTO ModeloVehiculos VALUES (889, 72, 'Tagora')
INSERT INTO ModeloVehiculos VALUES (890, 72, 'Solara')
INSERT INTO ModeloVehiculos VALUES (891, 72, 'Horizon')
INSERT INTO ModeloVehiculos VALUES (892, 73, 'Telcosport')
INSERT INTO ModeloVehiculos VALUES (893, 73, 'Telco')
INSERT INTO ModeloVehiculos VALUES (894, 73, 'Sumo')
INSERT INTO ModeloVehiculos VALUES (895, 73, 'Safari')
INSERT INTO ModeloVehiculos VALUES (896, 73, 'Indica')
INSERT INTO ModeloVehiculos VALUES (897, 73, 'Indigo')
INSERT INTO ModeloVehiculos VALUES (898, 73, 'Grand Safari')
INSERT INTO ModeloVehiculos VALUES (899, 73, 'Tl Pick Up')
INSERT INTO ModeloVehiculos VALUES (900, 73, 'Xenon Pick Up')
INSERT INTO ModeloVehiculos VALUES (901, 73, 'Vista')
INSERT INTO ModeloVehiculos VALUES (902, 73, 'Xenon')
INSERT INTO ModeloVehiculos VALUES (903, 73, 'Aria')
INSERT INTO ModeloVehiculos VALUES (904, 74, 'Carina E')
INSERT INTO ModeloVehiculos VALUES (905, 74, '4runner')
INSERT INTO ModeloVehiculos VALUES (906, 74, 'Camry')
INSERT INTO ModeloVehiculos VALUES (907, 74, 'Rav4')
INSERT INTO ModeloVehiculos VALUES (908, 74, 'Celica')
INSERT INTO ModeloVehiculos VALUES (909, 74, 'Supra')
INSERT INTO ModeloVehiculos VALUES (910, 74, 'Paseo')
INSERT INTO ModeloVehiculos VALUES (911, 74, 'Land Cruiser 80')
INSERT INTO ModeloVehiculos VALUES (912, 74, 'Land Cruiser 100')
INSERT INTO ModeloVehiculos VALUES (913, 74, 'Land Cruiser')
INSERT INTO ModeloVehiculos VALUES (914, 74, 'Land Cruiser 90')
INSERT INTO ModeloVehiculos VALUES (915, 74, 'Corolla')
INSERT INTO ModeloVehiculos VALUES (916, 74, 'Auris')
INSERT INTO ModeloVehiculos VALUES (917, 74, 'Avensis')
INSERT INTO ModeloVehiculos VALUES (918, 74, 'Picnic')
INSERT INTO ModeloVehiculos VALUES (919, 74, 'Yaris')
INSERT INTO ModeloVehiculos VALUES (920, 74, 'Yaris Verso')
INSERT INTO ModeloVehiculos VALUES (921, 74, 'Mr2')
INSERT INTO ModeloVehiculos VALUES (922, 74, 'Previa')
INSERT INTO ModeloVehiculos VALUES (923, 74, 'Prius')
INSERT INTO ModeloVehiculos VALUES (924, 74, 'Avensis Verso')
INSERT INTO ModeloVehiculos VALUES (925, 74, 'Corolla Verso')
INSERT INTO ModeloVehiculos VALUES (926, 74, 'Corolla Sedan')
INSERT INTO ModeloVehiculos VALUES (927, 74, 'Aygo')
INSERT INTO ModeloVehiculos VALUES (928, 74, 'Hilux')
INSERT INTO ModeloVehiculos VALUES (929, 74, 'Dyna')
INSERT INTO ModeloVehiculos VALUES (930, 74, 'Land Cruiser 200')
INSERT INTO ModeloVehiculos VALUES (931, 74, 'Verso')
INSERT INTO ModeloVehiculos VALUES (932, 74, 'Iq')
INSERT INTO ModeloVehiculos VALUES (933, 74, 'Urban Cruiser')
INSERT INTO ModeloVehiculos VALUES (934, 74, 'Gt86')
INSERT INTO ModeloVehiculos VALUES (935, 75, '100')
INSERT INTO ModeloVehiculos VALUES (936, 75, '121')
INSERT INTO ModeloVehiculos VALUES (937, 76, '214')
INSERT INTO ModeloVehiculos VALUES (938, 76, '110 Stawra')
INSERT INTO ModeloVehiculos VALUES (939, 76, '111 Stawra')
INSERT INTO ModeloVehiculos VALUES (940, 76, '215')
INSERT INTO ModeloVehiculos VALUES (941, 76, '112 Stawra')
INSERT INTO ModeloVehiculos VALUES (942, 77, 'Passat')
INSERT INTO ModeloVehiculos VALUES (943, 77, 'Golf')
INSERT INTO ModeloVehiculos VALUES (944, 77, 'Vento')
INSERT INTO ModeloVehiculos VALUES (945, 77, 'Polo')
INSERT INTO ModeloVehiculos VALUES (946, 77, 'Corrado')
INSERT INTO ModeloVehiculos VALUES (947, 77, 'Sharan')
INSERT INTO ModeloVehiculos VALUES (948, 77, 'Lupo')
INSERT INTO ModeloVehiculos VALUES (949, 77, 'Bora')
INSERT INTO ModeloVehiculos VALUES (950, 77, 'Jetta')
INSERT INTO ModeloVehiculos VALUES (951, 77, 'New Beetle')
INSERT INTO ModeloVehiculos VALUES (952, 77, 'Phaeton')
INSERT INTO ModeloVehiculos VALUES (953, 77, 'Touareg')
INSERT INTO ModeloVehiculos VALUES (954, 77, 'Touran')
INSERT INTO ModeloVehiculos VALUES (955, 77, 'Multivan')
INSERT INTO ModeloVehiculos VALUES (956, 77, 'Caddy')
INSERT INTO ModeloVehiculos VALUES (957, 77, 'Golf Plus')
INSERT INTO ModeloVehiculos VALUES (958, 77, 'Fox')
INSERT INTO ModeloVehiculos VALUES (959, 77, 'Eos')
INSERT INTO ModeloVehiculos VALUES (960, 77, 'Caravelle')
INSERT INTO ModeloVehiculos VALUES (961, 77, 'Tiguan')
INSERT INTO ModeloVehiculos VALUES (962, 77, 'Transporter')
INSERT INTO ModeloVehiculos VALUES (963, 77, 'Lt')
INSERT INTO ModeloVehiculos VALUES (964, 77, 'Taro')
INSERT INTO ModeloVehiculos VALUES (965, 77, 'Crafter')
INSERT INTO ModeloVehiculos VALUES (966, 77, 'California')
INSERT INTO ModeloVehiculos VALUES (967, 77, 'Santana')
INSERT INTO ModeloVehiculos VALUES (968, 77, 'Scirocco')
INSERT INTO ModeloVehiculos VALUES (969, 77, 'Passat Cc')
INSERT INTO ModeloVehiculos VALUES (970, 77, 'Amarok')
INSERT INTO ModeloVehiculos VALUES (971, 77, 'Beetle')
INSERT INTO ModeloVehiculos VALUES (972, 77, 'Up')
INSERT INTO ModeloVehiculos VALUES (973, 77, 'Cc')
INSERT INTO ModeloVehiculos VALUES (974, 78, '440')
INSERT INTO ModeloVehiculos VALUES (975, 78, '850')
INSERT INTO ModeloVehiculos VALUES (976, 78, 'S70')
INSERT INTO ModeloVehiculos VALUES (977, 78, 'V70')
INSERT INTO ModeloVehiculos VALUES (978, 78, 'V70 Classic')
INSERT INTO ModeloVehiculos VALUES (979, 78, '940')
INSERT INTO ModeloVehiculos VALUES (980, 78, '480')
INSERT INTO ModeloVehiculos VALUES (981, 78, '460')
INSERT INTO ModeloVehiculos VALUES (982, 78, '960')
INSERT INTO ModeloVehiculos VALUES (983, 78, 'S90')
INSERT INTO ModeloVehiculos VALUES (984, 78, 'V90')
INSERT INTO ModeloVehiculos VALUES (985, 78, 'Classic')
INSERT INTO ModeloVehiculos VALUES (986, 78, 'S40')
INSERT INTO ModeloVehiculos VALUES (987, 78, 'V40')
INSERT INTO ModeloVehiculos VALUES (988, 78, 'V50')
INSERT INTO ModeloVehiculos VALUES (989, 78, 'V70 Xc')
INSERT INTO ModeloVehiculos VALUES (990, 78, 'Xc70')
INSERT INTO ModeloVehiculos VALUES (991, 78, 'C70')
INSERT INTO ModeloVehiculos VALUES (992, 78, 'S80')
INSERT INTO ModeloVehiculos VALUES (993, 78, 'S60')
INSERT INTO ModeloVehiculos VALUES (994, 78, 'Xc90')
INSERT INTO ModeloVehiculos VALUES (995, 78, 'C30')
INSERT INTO ModeloVehiculos VALUES (996, 78, '780')
INSERT INTO ModeloVehiculos VALUES (997, 78, '760')
INSERT INTO ModeloVehiculos VALUES (998, 78, '740')
INSERT INTO ModeloVehiculos VALUES (999, 78, '240')
INSERT INTO ModeloVehiculos VALUES (1000, 78, '360')
INSERT INTO ModeloVehiculos VALUES (1001, 78, '340')
INSERT INTO ModeloVehiculos VALUES (1002, 78, 'Xc60')
INSERT INTO ModeloVehiculos VALUES (1003, 78, 'V60')
INSERT INTO ModeloVehiculos VALUES (1004, 78, 'V40 Cross Country')
INSERT INTO ModeloVehiculos VALUES (1005, 79, '353')
INSERT INTO ModeloVehiculos VALUES (1006, 53, 'Mini')
INSERT INTO ModeloVehiculos VALUES (1007, 53, 'Countryman')
INSERT INTO ModeloVehiculos VALUES (1008, 53, 'Paceman')
